In [1]:
import pandas as pd

In [2]:
# List of London borough names
london_boroughs = [
    "Barking and Dagenham", "Barnet", "Bexley", "Brent", "Bromley",
    "Camden", "City of London", "Croydon", "Ealing", "Enfield", "Greenwich",
    "Hackney", "Hammersmith and Fulham", "Haringey", "Harrow", "Havering",
    "Hillingdon", "Hounslow", "Islington", "Kensington and Chelsea", "Kingston upon Thames",
    "Lambeth", "Lewisham", "Merton", "Newham", "Redbridge",
    "Richmond upon Thames", "Southwark", "Sutton", "Tower Hamlets", "Waltham Forest",
    "Wandsworth", "Westminster"
    ]

In [3]:
df = pd.read_csv("../Dataset/LSOA Best-Fit Lookup (2001-2011-2021)/LSOA_(2011)_to_LSOA_(2021)_to_Local_Authority_District_(2022)_Exact_Fit_Lookup_for_EW_(V3).csv")

In [4]:
# Select the data for the London area 
df = df[df['LAD22CD'].str.startswith('E09')]
df.drop(columns=['LAD22NMW'], inplace=True)

In [5]:
df

,LSOA11CD,LSOA11NM,LSOA21CD,LSOA21NM,CHGIND,LAD22CD,LAD22NM,ObjectId
476,E01000027,Barking and Dagenham 001A,E01000027,Barking and Dagenham 001A,U,E09000002,Barking and Dagenham,477
477,E01000028,Barking and Dagenham 001B,E01000028,Barking and Dagenham 001B,U,E09000002,Barking and Dagenham,478
478,E01000029,Barking and Dagenham 001C,E01000029,Barking and Dagenham 001C,U,E09000002,Barking and Dagenham,479
479,E01000030,Barking and Dagenham 001D,E01000030,Barking and Dagenham 001D,U,E09000002,Barking and Dagenham,480
480,E01000031,Barking and Dagenham 002A,E01000031,Barking and Dagenham 002A,U,E09000002,Barking and Dagenham,481
...,...,...,...,...,...,...,...,...
33986,E01004712,Westminster 008C,E01004712,Westminster 008C,U,E09000033,Westminster,33987
33989,E01004727,Westminster 008D,E01004727,Westminster 008D,U,E09000033,Westminster,33990
33992,E01004670,Westminster 009A,E01004670,Westminster 009A,U,E09000033,Westminster,33993
33994,E01004702,Westminster 009E,E01004702,Westminster 009E,U,E09000033,Westminster,33995
33996,E01033598,Westminster 009F,E01033598,Westminster 009F,U,E09000033,Westminster,33997

In [6]:
counts_lsoa_2021 = df['LSOA21CD'].value_counts().reset_index()
counts_lsoa_2021.columns = ['Element', 'Count']

print(counts_lsoa_2021)

        Element  Count
0     E01034173      2
1     E01035710      2
2     E01035711      2
3     E01033926      2
4     E01035712      2
...         ...    ...
4989  E01004712      1
4990  E01004727      1
4991  E01004670      1
4992  E01004702      1
4993  E01033598      1

[4994 rows x 2 columns]

In [7]:
counts_lsoa_2011 = df['LSOA11CD'].value_counts().reset_index()
counts_lsoa_2011.columns = ['Element', 'Count']

print(counts_lsoa_2011)

        Element  Count
0     E01033583      9
1     E01033577      5
2     E01004562      4
3     E01004215      4
4     E01033572      4
...         ...    ...
4830  E01004693      1
4831  E01004709      1
4832  E01004652      1
4833  E01004705      1
4834  E01000100      1

[4835 rows x 2 columns]

In [8]:
counts_change_2011_2021 = df['CHGIND'].value_counts().reset_index()
counts_change_2011_2021.columns = ['Element', 'Count']

print(counts_change_2011_2021)

  Element  Count
0       U   4659
1       S    313
2       M     44

In [9]:
df_lsoa_U_2011_2021 = df[df['CHGIND'] == 'U']

In [10]:
df_lsoa_U_2011_2021

,LSOA11CD,LSOA11NM,LSOA21CD,LSOA21NM,CHGIND,LAD22CD,LAD22NM,ObjectId
476,E01000027,Barking and Dagenham 001A,E01000027,Barking and Dagenham 001A,U,E09000002,Barking and Dagenham,477
477,E01000028,Barking and Dagenham 001B,E01000028,Barking and Dagenham 001B,U,E09000002,Barking and Dagenham,478
478,E01000029,Barking and Dagenham 001C,E01000029,Barking and Dagenham 001C,U,E09000002,Barking and Dagenham,479
479,E01000030,Barking and Dagenham 001D,E01000030,Barking and Dagenham 001D,U,E09000002,Barking and Dagenham,480
480,E01000031,Barking and Dagenham 002A,E01000031,Barking and Dagenham 002A,U,E09000002,Barking and Dagenham,481
...,...,...,...,...,...,...,...,...
33986,E01004712,Westminster 008C,E01004712,Westminster 008C,U,E09000033,Westminster,33987
33989,E01004727,Westminster 008D,E01004727,Westminster 008D,U,E09000033,Westminster,33990
33992,E01004670,Westminster 009A,E01004670,Westminster 009A,U,E09000033,Westminster,33993
33994,E01004702,Westminster 009E,E01004702,Westminster 009E,U,E09000033,Westminster,33995
33996,E01033598,Westminster 009F,E01033598,Westminster 009F,U,E09000033,Westminster,33997

In [11]:
# Select the columns needed in the analysis
selected_columns = ['LSOA11CD', 'LSOA21CD', 'LAD22CD', 'LAD22NM']
df_lsoa_U_2011_2021 = df_lsoa_U_2011_2021[selected_columns]

In [12]:
df_lsoa_U_2011_2021.to_csv('../Output/lsoa_2011_to_2021_unchnaged.csv', index=False)

In [13]:
df_ = pd.read_excel("../Dataset/LSOA Best-Fit Lookup (2001-2011-2021)/2001_to_2011_OA-LSOA-MSOA-WARD-BOROUGH.xls", engine='xlrd', sheet_name='LSOA')

In [14]:
# The format is usually like "Camden 001A", so we extract the part before the first number
df_["borough_name"] = df_["LSOA11NM"].str.extract(r"^([A-Za-z \-&']+?)\s+\d")

# Remove any leading or trailing whitespace
df_["borough_name"] = df_["borough_name"].str.strip()

# Filter rows where the extracted borough name is in the official list
df_ = df_[df_["borough_name"].isin(london_boroughs)]

df_.drop(columns=["borough_name"], inplace=True)

In [15]:
df_

       LSOA01CD             LSOA01NM   LSOA11CD             LSOA11NM CHGIND
0     E01000001  City of London 001A  E01000001  City of London 001A      U
1     E01000002  City of London 001B  E01000002  City of London 001B      U
2     E01000003  City of London 001C  E01000003  City of London 001C      U
3     E01000004  City of London 001D  E01032739  City of London 001F      S
4     E01000004  City of London 001D  E01032740  City of London 001G      S
...         ...                  ...        ...                  ...    ...
4848  E01004762     Westminster 011E  E01004762     Westminster 011E      U
4849  E01004763     Westminster 013B  E01004763     Westminster 013B      U
4850  E01004764     Westminster 013C  E01033595     Westminster 013E      S
4851  E01004764     Westminster 013C  E01033596     Westminster 013F      S
4852  E01004765     Westminster 013D  E01004765     Westminster 013D      U

[4853 rows x 5 columns]

In [16]:
counts_2011_ = df_['LSOA11NM'].value_counts().reset_index()
counts_2011_.columns = ['Element', 'Count']

print(counts_2011_)

                  Element  Count
0          Greenwich 034E      4
1              Brent 010F      2
2              Brent 003G      2
3            Hackney 002F      2
4              Brent 027F      2
...                   ...    ...
4830     Westminster 011E      1
4831     Westminster 013B      1
4832     Westminster 013E      1
4833     Westminster 013F      1
4834  City of London 001C      1

[4835 rows x 2 columns]

In [17]:
counts_2001 = df_['LSOA01NM'].value_counts().reset_index()
counts_2001.columns = ['Element', 'Count']

print(counts_2001)

                          Element  Count
0                  Greenwich 004A      5
1              Tower Hamlets 028C      5
2              Tower Hamlets 029B      5
3                     Newham 034B      4
4     Hammersmith and Fulham 023B      3
...                           ...    ...
4760             Westminster 018D      1
4761             Westminster 011E      1
4762             Westminster 013B      1
4763    Barking and Dagenham 016D      1
4764             Westminster 018A      1

[4765 rows x 2 columns]

In [18]:
counts_change_2001_2011 = df_['CHGIND'].value_counts().reset_index()
counts_change_2001_2011.columns = ['Element', 'Count']

print(counts_change_2001_2011)

  Element  Count
0       U   4642
1       S    152
2       M     32
3       X     27

In [19]:
df_lsoa_U_2001_2011 = df_[df_['CHGIND'] == 'U']

In [20]:
df_lsoa_U_2001_2011

,LSOA01CD,LSOA01NM,LSOA11CD,LSOA11NM,CHGIND
0,E01000001,City of London 001A,E01000001,City of London 001A,U
1,E01000002,City of London 001B,E01000002,City of London 001B,U
2,E01000003,City of London 001C,E01000003,City of London 001C,U
5,E01000005,City of London 001E,E01000005,City of London 001E,U
6,E01000006,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,U
...,...,...,...,...,...
4846,E01004760,Westminster 014E,E01004760,Westminster 014E,U
4847,E01004761,Westminster 018D,E01004761,Westminster 018D,U
4848,E01004762,Westminster 011E,E01004762,Westminster 011E,U
4849,E01004763,Westminster 013B,E01004763,Westminster 013B,U
4852,E01004765,Westminster 013D,E01004765,Westminster 013D,U

In [21]:
df_lsoa_U_2001_2021 = pd.merge(df_lsoa_U_2001_2011, df_lsoa_U_2011_2021, left_on='LSOA11CD', right_on='LSOA11CD', how='left')
df_lsoa_U_2001_2021.dropna(subset=['LSOA21CD'], inplace=True)

In [22]:
df_lsoa_U_2001_2021

,LSOA01CD,LSOA01NM,LSOA11CD,LSOA11NM,CHGIND,LSOA21CD,LAD22CD,LAD22NM
0,E01000001,City of London 001A,E01000001,City of London 001A,U,E01000001,E09000001,City of London
1,E01000002,City of London 001B,E01000002,City of London 001B,U,E01000002,E09000001,City of London
2,E01000003,City of London 001C,E01000003,City of London 001C,U,E01000003,E09000001,City of London
3,E01000005,City of London 001E,E01000005,City of London 001E,U,E01000005,E09000001,City of London
4,E01000006,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,U,E01000006,E09000002,Barking and Dagenham
...,...,...,...,...,...,...,...,...
4637,E01004760,Westminster 014E,E01004760,Westminster 014E,U,E01004760,E09000033,Westminster
4638,E01004761,Westminster 018D,E01004761,Westminster 018D,U,E01004761,E09000033,Westminster
4639,E01004762,Westminster 011E,E01004762,Westminster 011E,U,E01004762,E09000033,Westminster
4640,E01004763,Westminster 013B,E01004763,Westminster 013B,U,E01004763,E09000033,Westminster
4641,E01004765,Westminster 013D,E01004765,Westminster 013D,U,E01004765,E09000033,Westminster

In [23]:
# Select the columns needed in the analysis
selected_columns = ['LSOA01CD', 'LSOA11CD', 'LSOA21CD', 'LAD22CD', 'LAD22NM']
df_lsoa_U_2001_2021 = df_lsoa_U_2001_2021[selected_columns]

In [24]:
df_lsoa_U_2001_2021

       LSOA01CD   LSOA11CD   LSOA21CD    LAD22CD               LAD22NM
0     E01000001  E01000001  E01000001  E09000001        City of London
1     E01000002  E01000002  E01000002  E09000001        City of London
2     E01000003  E01000003  E01000003  E09000001        City of London
3     E01000005  E01000005  E01000005  E09000001        City of London
4     E01000006  E01000006  E01000006  E09000002  Barking and Dagenham
...         ...        ...        ...        ...                   ...
4637  E01004760  E01004760  E01004760  E09000033           Westminster
4638  E01004761  E01004761  E01004761  E09000033           Westminster
4639  E01004762  E01004762  E01004762  E09000033           Westminster
4640  E01004763  E01004763  E01004763  E09000033           Westminster
4641  E01004765  E01004765  E01004765  E09000033           Westminster

[4506 rows x 5 columns]

In [25]:
df_lsoa_U_2001_2021.to_csv('../Output/lsoa_2001_to_2021_unchnaged.csv', index=False)