In [53]:
import pandas as pd

In [54]:
# Themes to load
themes = ["Tenure(H)", "Ethnic_group", "NS-SeC", "Education", "Occupation"]

# Base directories
data_dir_2011 = "../Dataset/Census London 2011/"
data_dir_2021 = "../Dataset/Census London 2021/"

# Merge key
merge_key = "LSOA21CD"

# Dictionary to store each theme's merged data
merged_data = {}

for theme in themes:
    # Construct file paths
    file_2011 = f"{data_dir_2011}{theme}_2011 mapped.csv"
    file_2021 = f"{data_dir_2021}{theme}_2021.csv"

    try:
        # Load data
        df_2011 = pd.read_csv(file_2011).dropna(axis=1, how="all")
        df_2021 = pd.read_csv(file_2021).dropna(axis=1, how="all")

        # Remove 'Borough' column from 2021 data if it exists
        if "Borough" in df_2021.columns:
            df_2021.drop(columns=["Borough"], inplace=True)

        # Add suffixes to all columns except the merge key
        df_2011 = df_2011.rename(columns={col: col + "_2011" for col in df_2011.columns if col != merge_key})
        df_2021 = df_2021.rename(columns={col: col + "_2021" for col in df_2021.columns if col != merge_key})

        # Merge 2011 and 2021 data for this theme
        df_merged = pd.merge(df_2011, df_2021, on=merge_key, how="outer")

        # Store result
        merged_data[theme] = df_merged

        print(f"Successfully loaded and merged: {theme}")

    except Exception as e:
        print(f"Error processing {theme}: {e}")


# Combine all themes into a single DataFrame
df_census = list(merged_data.values())[0]
for df in list(merged_data.values())[1:]:
    df_census = pd.merge(df_census, df, on=merge_key, how="outer")

Successfully loaded and merged: Tenure(H)
Successfully loaded and merged: Ethnic_group
Successfully loaded and merged: NS-SeC
Successfully loaded and merged: Education
Successfully loaded and merged: Occupation

In [55]:
df_property_sales = pd.read_csv("../Dataset/Other Datasets/Number of sales mapped.csv")

In [56]:
df_census = df_census.merge(df_property_sales, left_on='LSOA21CD', right_on='LSOA21CD')

In [57]:
df_census

,LSOA21CD,All households_weighted_2011,Owned_weighted_2011,Owned: Owned outright_weighted_2011,Owned: Owned with a mortgage or loan_weighted_2011,Shared ownership (part owned and part rented)_weighted_2011,Social rented_weighted_2011,Social rented: Rented from council (Local Authority)_weighted_2011,Social rented: Other_weighted_2011,Private rented_weighted_2011,...,2. Professional occupations_2021,3. Associate professional and technical occupations_2021,4. Administrative and secretarial occupations_2021,5. Skilled trades occupations_2021,"6. Caring, leisure and other service occupations_2021",7. Sales and customer service occupations_2021,"8. Process, plant and machine operatives_2021",9. Elementary occupations_2021,Number of sales 2011_weighted,Number of sales 2021_weighted
0,E01000001,876.0,533.0,355.0,178.0,3.0,41.0,33.0,8.0,264.0,...,407.0,185.0,38.0,5.0,20.0,14.0,6.0,4.0,141.0,123.0
1,E01000002,830.0,527.0,314.0,213.0,8.0,48.0,44.0,4.0,219.0,...,417.0,187.0,35.0,3.0,5.0,3.0,3.0,7.0,233.0,144.0
2,E01000003,817.0,327.0,184.0,143.0,1.0,295.0,239.0,56.0,177.0,...,390.0,215.0,72.0,28.0,27.0,26.0,10.0,42.0,168.0,95.0
3,E01000005,467.0,46.0,24.0,22.0,0.0,312.0,133.0,179.0,101.0,...,129.0,59.0,45.0,21.0,52.0,34.0,16.0,86.0,41.0,10.0
4,E01000006,543.0,345.0,136.0,209.0,0.0,18.0,11.0,7.0,178.0,...,126.0,99.0,68.0,107.0,82.0,68.0,101.0,161.0,44.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,996.0,502.0,380.0,122.0,4.0,44.0,7.0,37.0,363.0,...,226.0,243.0,38.0,11.0,41.0,13.0,13.0,37.0,189.0,113.0
4990,E01035719,528.0,193.0,103.0,90.0,10.0,156.0,95.0,61.0,151.0,...,231.0,119.0,47.0,10.0,47.0,29.0,13.0,18.0,75.0,41.0
4991,E01035720,597.0,218.0,117.0,101.0,12.0,176.0,107.0,69.0,170.0,...,203.0,101.0,65.0,17.0,41.0,61.0,24.0,42.0,84.0,46.0
4992,E01035721,1296.0,294.0,186.0,108.0,19.0,601.0,272.0,329.0,362.0,...,285.0,192.0,69.0,34.0,101.0,59.0,32.0,55.0,100.0,89.0
4993,E01035722,1672.0,319.0,201.0,118.0,0.0,150.0,26.0,124.0,1172.0,...,464.0,218.0,84.0,36.0,28.0,36.0,15.0,26.0,112.0,99.0

In [58]:
print(df_census.columns.to_list())

['LSOA21CD', 'All households_weighted_2011', 'Owned_weighted_2011', 'Owned: Owned outright_weighted_2011', 'Owned: Owned with a mortgage or loan_weighted_2011', 'Shared ownership (part owned and part rented)_weighted_2011', 'Social rented_weighted_2011', 'Social rented: Rented from council (Local Authority)_weighted_2011', 'Social rented: Other_weighted_2011', 'Private rented_weighted_2011', 'Private rented: Private landlord or letting agency_weighted_2011', 'Private rented: Other_weighted_2011', 'Living rent free_weighted_2011', 'Total: All households_2021', 'Owned_2021', 'Owned: Owns outright_2021', 'Owned: Owns with a mortgage or loan_2021', 'Shared ownership_2021', 'Shared ownership: Shared ownership_2021', 'Social rented_2021', 'Social rented: Rents from council or Local Authority_2021', 'Social rented: Other social rented_2021', 'Private rented_2021', 'Private rented: Private landlord or letting agency_2021', 'Private rented: Other private rented_2021', 'Lives rent free_2021', 'Owns with a mortgage or loan or shared ownership_2021', 'Private rented or lives rent free_2021', 'All usual residents_weighted_2011', 'White_weighted_2011', 'White: English/Welsh/Scottish/Northern Irish/British_weighted_2011', 'White: Irish_weighted_2011', 'White: Gypsy or Irish Traveller_weighted_2011', 'White: Other White_weighted_2011', 'Mixed/multiple ethnic groups_weighted_2011', 'Mixed/multiple ethnic groups: White and Black Caribbean_weighted_2011', 'Mixed/multiple ethnic groups: White and Black African_weighted_2011', 'Mixed/multiple ethnic groups: White and Asian_weighted_2011', 'Mixed/multiple ethnic groups: Other Mixed_weighted_2011', 'Asian/Asian British_weighted_2011', 'Asian/Asian British: Indian_weighted_2011', 'Asian/Asian British: Pakistani_weighted_2011', 'Asian/Asian British: Bangladeshi_weighted_2011', 'Asian/Asian British: Chinese_weighted_2011', 'Asian/Asian British: Other Asian_weighted_2011', 'Black/African/Caribbean/Black British_weighted_2011', 'Black/African/Caribbean/Black British: African_weighted_2011', 'Black/African/Caribbean/Black British: Caribbean_weighted_2011', 'Black/African/Caribbean/Black British: Other Black_weighted_2011', 'Other ethnic group_weighted_2011', 'Other ethnic group: Arab_weighted_2011', 'Other ethnic group: Any other ethnic group_weighted_2011', 'Total: All usual residents_2021', 'Asian, Asian British or Asian Welsh_2021', 'Asian, Asian British or Asian Welsh: Bangladeshi_2021', 'Asian, Asian British or Asian Welsh: Chinese_2021', 'Asian, Asian British or Asian Welsh: Indian_2021', 'Asian, Asian British or Asian Welsh: Pakistani_2021', 'Asian, Asian British or Asian Welsh: Other Asian_2021', 'Black, Black British, Black Welsh, Caribbean or African_2021', 'Black, Black British, Black Welsh, Caribbean or African: African_2021', 'Black, Black British, Black Welsh, Caribbean or African: Caribbean_2021', 'Black, Black British, Black Welsh, Caribbean or African: Other Black_2021', 'Mixed or Multiple ethnic groups_2021', 'Mixed or Multiple ethnic groups: White and Asian_2021', 'Mixed or Multiple ethnic groups: White and Black African_2021', 'Mixed or Multiple ethnic groups: White and Black Caribbean_2021', 'Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups_2021', 'White_2021', 'White: English, Welsh, Scottish, Northern Irish or British_2021', 'White: Irish_2021', 'White: Gypsy or Irish Traveller_2021', 'White: Roma_2021', 'White: Other White_2021', 'Other ethnic group_2021', 'Other ethnic group: Arab_2021', 'Other ethnic group: Any other ethnic group_2021', 'All categories: NS-SeC_weighted_2011', '1. Higher managerial, administrative and professional occupations_weighted_2011', '2. Lower managerial, administrative and professional occupations_weighted_2011', '3. Intermediate occupations_weighted_2011', '4. Small employers and own account workers_weighted_2011', '5. Lower supervisory and technical occupations_weighted_2011', '6. Semi-routine occupations_weighted_2011', '7. Routine occupations_weighted_2011', '8. Never worked and long-term unemployed_weighted_2011', 'Not classified_weighted_2011', 'Total: All usual residents aged 16 years and over_2021_x', 'L1, L2 and L3 Higher managerial, administrative and professional occupations_2021', 'L4, L5 and L6 Lower managerial, administrative and professional occupations_2021', 'L7 Intermediate occupations_2021', 'L8 and L9 Small employers and own account workers_2021', 'L10 and L11 Lower supervisory and technical occupations_2021', 'L12 Semi-routine occupations_2021', 'L13 Routine occupations_2021', 'L14.1 and L14.2 Never worked and long-term unemployed_2021', 'L15 Full-time students_2021', 'All categories: Highest level of qualification_weighted_2011', 'No qualifications_weighted_2011', 'Highest level of qualification: Level 1 qualifications_weighted_2011', 'Highest level of qualification: Level 2 qualifications_weighted_2011', 'Highest level of qualification: Apprenticeship_weighted_2011', 'Highest level of qualification: Level 3 qualifications_weighted_2011', 'Highest level of qualification: Level 4 qualifications and above_weighted_2011', 'Highest level of qualification: Other qualifications_weighted_2011', 'Schoolchildren and full-time students: Age 16 to 17_weighted_2011', 'Schoolchildren and full-time students: Age 18 and over_weighted_2011', 'Full-time students: Age 18 to 74: Economically active: In employment_weighted_2011', 'Full-time students: Age 18 to 74: Economically active: Unemployed_weighted_2011', 'Full-time students: Age 18 to 74: Economically inactive_weighted_2011', 'Total: All usual residents aged 16 years and over_2021_y', 'No qualifications_2021', 'Level 1 and entry level qualifications_2021', 'Level 2 qualifications_2021', 'Apprenticeship_2021', 'Level 3 qualifications_2021', 'Level 4 qualifications or above_2021', 'Other qualifications_2021', 'All categories: Occupation_weighted_2011', '1. Managers, directors and senior officials_weighted_2011', '2. Professional occupations_weighted_2011', '3. Associate professional and technical occupations_weighted_2011', '4. Administrative and secretarial occupations_weighted_2011', '5. Skilled trades occupations_weighted_2011', '6. Caring, leisure and other service occupations_weighted_2011', '7. Sales and customer service occupations_weighted_2011', '8. Process plant and machine operatives_weighted_2011', '9. Elementary occupations_weighted_2011', 'Total: All usual residents aged 16 years and over in employment the week before the census_2021', '1. Managers, directors and senior officials_2021', '2. Professional occupations_2021', '3. Associate professional and technical occupations_2021', '4. Administrative and secretarial occupations_2021', '5. Skilled trades occupations_2021', '6. Caring, leisure and other service occupations_2021', '7. Sales and customer service occupations_2021', '8. Process, plant and machine operatives_2021', '9. Elementary occupations_2021', 'Number of sales 2011_weighted', 'Number of sales 2021_weighted']

In [59]:
df_census['pct_high_education_2011'] = df_census['Highest level of qualification: Level 4 qualifications and above_weighted_2011'] / df_census['All categories: Highest level of qualification_weighted_2011']
df_census['pct_high_education_2021'] = df_census['Level 4 qualifications or above_2021'] / df_census['Total: All usual residents aged 16 years and over_2021_x']
df_census['delta_high_education'] = df_census['pct_high_education_2021'] - df_census['pct_high_education_2011']

In [60]:
df_census['pct_owner_occupied_2011'] = df_census['Owned_weighted_2011']  / df_census['All households_weighted_2011']
df_census['pct_owner_occupied_2021'] = df_census['Owned_2021']  / df_census['Total: All households_2021']
df_census['delta_owner_occupied'] = df_census['pct_owner_occupied_2021'] - df_census['pct_owner_occupied_2011']

In [61]:
df_census['pct_private_rented_2011'] = df_census['Private rented_weighted_2011']  / df_census['All households_weighted_2011']
df_census['pct_private_rented_2021'] = df_census['Private rented_2021']  / df_census['Total: All households_2021']
df_census['delta_private_rented'] = df_census['pct_private_rented_2021'] - df_census['pct_private_rented_2011']

In [62]:
df_census['pct_social_rented_2011'] = df_census['Social rented_weighted_2011'] / df_census['All households_weighted_2011']
df_census['pct_social_rented_2021'] = df_census['Social rented_2021'] / df_census['Total: All households_2021']
df_census['delta_social_rented'] = df_census['pct_social_rented_2021'] - df_census['pct_social_rented_2011']

In [63]:
df_census['pct_renters_2011'] = df_census['pct_social_rented_2011'] + df_census['pct_private_rented_2011']
df_census['pct_renters_2021'] = df_census['pct_social_rented_2021'] + df_census['pct_private_rented_2021']
df_census['delta_renters'] = df_census['pct_renters_2021'] - df_census['pct_renters_2011']

In [64]:
df_census['pct_professional_2011'] = (df_census['1. Managers, directors and senior officials_weighted_2011'] + 
                                      df_census['2. Professional occupations_weighted_2011']) / df_census['All categories: Occupation_weighted_2011']
df_census['pct_professional_2021'] = (df_census['1. Managers, directors and senior officials_2021'] + df_census['2. Professional occupations_2021']) / df_census['Total: All usual residents aged 16 years and over in employment the week before the census_2021']
df_census['delta_professional'] = df_census['pct_professional_2021'] - df_census['pct_professional_2011']

In [65]:
df_census['pct_low_skill_2011'] = (df_census['8. Process plant and machine operatives_weighted_2011'] +
                                   df_census['9. Elementary occupations_weighted_2011']) / df_census['All categories: Occupation_weighted_2011']
df_census['pct_low_skill_2021'] = (df_census['8. Process, plant and machine operatives_2021'] +
                                   df_census['9. Elementary occupations_2021']) / df_census['Total: All usual residents aged 16 years and over in employment the week before the census_2021']
df_census['delta_low_skill'] = df_census['pct_low_skill_2021'] - df_census['pct_low_skill_2011']

In [66]:
df_census['pct_high_sec_2011'] = (df_census['1. Higher managerial, administrative and professional occupations_weighted_2011'] +
                                  df_census['2. Lower managerial, administrative and professional occupations_weighted_2011']) / df_census['All categories: NS-SeC_weighted_2011']
df_census['pct_high_sec_2021'] = (df_census['L1, L2 and L3 Higher managerial, administrative and professional occupations_2021'] +
                                  df_census['L4, L5 and L6 Lower managerial, administrative and professional occupations_2021']) / df_census['Total: All usual residents aged 16 years and over_2021_x'] # same as 'Total: All usual residents aged 16 years and over_2021_y'
df_census['delta_high_sec'] = df_census['pct_high_sec_2021'] - df_census['pct_high_sec_2011']

In [67]:
df_census['pct_low_sec_2011'] = (df_census['6. Semi-routine occupations_weighted_2011'] +
                                 df_census['7. Routine occupations_weighted_2011'] +
                                 df_census['8. Never worked and long-term unemployed_weighted_2011']) / df_census['All categories: NS-SeC_weighted_2011']
df_census['pct_low_sec_2021'] = (df_census['L12 Semi-routine occupations_2021'] +
                                 df_census['L13 Routine occupations_2021'] + 
                                 df_census['L14.1 and L14.2 Never worked and long-term unemployed_2021']) / df_census['Total: All usual residents aged 16 years and over_2021_x'] # same as 'Total: All usual residents aged 16 years and over_2021_y'
df_census['delta_low_sec'] = df_census['pct_low_sec_2021'] - df_census['pct_low_sec_2011']

In [68]:
df_census['pct_minority_ethnic_2011'] = (df_census['Mixed/multiple ethnic groups_weighted_2011'] + 
                                         df_census['Asian/Asian British_weighted_2011'] + 
                                         df_census['Black/African/Caribbean/Black British_weighted_2011'] + 
                                         df_census['Other ethnic group_weighted_2011']) / df_census['All usual residents_weighted_2011']
df_census['pct_minority_ethnic_2021'] = (df_census['Mixed or Multiple ethnic groups_2021'] + 
                                         df_census['Asian, Asian British or Asian Welsh_2021'] + 
                                         df_census['Black, Black British, Black Welsh, Caribbean or African_2021'] + 
                                         df_census['Other ethnic group_2021']) / df_census['Total: All usual residents_2021']
df_census['delta_minority_ethnic'] = df_census['pct_minority_ethnic_2021'] - df_census['pct_minority_ethnic_2011']

In [69]:
df_census['delta_property_sales'] = df_census['Number of sales 2021_weighted'] - df_census['Number of sales 2011_weighted']

In [70]:
df_census = df_census[['LSOA21CD', 
                'delta_property_sales', 
                'pct_minority_ethnic_2011', 'pct_minority_ethnic_2021', 'delta_minority_ethnic',
                'pct_owner_occupied_2011', 'pct_owner_occupied_2021', 'delta_owner_occupied',
                'pct_social_rented_2011', 'pct_social_rented_2021', 'delta_social_rented',
                'pct_private_rented_2011', 'pct_private_rented_2021', 'delta_private_rented',
                'pct_renters_2011', 'pct_renters_2021', 'delta_renters',
                'pct_high_education_2011','pct_high_education_2021','delta_high_education',
                'pct_high_sec_2011', 'pct_high_sec_2021', 'delta_high_sec',
                'pct_low_sec_2011', 'pct_low_sec_2021', 'delta_low_sec',
                'pct_professional_2011', 'pct_professional_2021', 'delta_professional', 
                'pct_low_skill_2011', 'pct_low_skill_2021', 'delta_low_skill']]

In [71]:
df_census

,LSOA21CD,delta_property_sales,pct_minority_ethnic_2011,pct_minority_ethnic_2021,delta_minority_ethnic,pct_owner_occupied_2011,pct_owner_occupied_2021,delta_owner_occupied,pct_social_rented_2011,pct_social_rented_2021,...,delta_high_sec,pct_low_sec_2011,pct_low_sec_2021,delta_low_sec,pct_professional_2011,pct_professional_2021,delta_professional,pct_low_skill_2011,pct_low_skill_2021,delta_low_skill
0,E01000001,-18.0,0.154949,0.198779,0.043830,0.608447,0.574671,-0.033776,0.046804,0.026284,...,-0.056471,0.044226,0.063516,0.019289,0.661987,0.688431,0.026444,0.015119,0.011455,-0.003664
1,E01000002,-89.0,0.112813,0.217893,0.105080,0.634940,0.524213,-0.110727,0.057831,0.032688,...,0.000485,0.035953,0.050038,0.014085,0.646154,0.723235,0.077081,0.017582,0.011390,-0.006193
2,E01000003,-73.0,0.216196,0.258685,0.042489,0.400245,0.372414,-0.027831,0.361077,0.297537,...,0.075057,0.152450,0.140770,-0.011680,0.489529,0.580000,0.090471,0.073298,0.052000,-0.021298
3,E01000005,-31.0,0.486294,0.614896,0.128601,0.098501,0.083682,-0.014819,0.668094,0.696653,...,-0.042427,0.338939,0.370062,0.031123,0.273109,0.366397,0.093288,0.199580,0.206478,0.006898
4,E01000006,14.0,0.672930,0.672087,-0.000843,0.635359,0.488246,-0.147113,0.033149,0.039783,...,-0.030783,0.330136,0.356394,0.026258,0.256082,0.226607,-0.029475,0.226633,0.295378,0.068745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,-76.0,0.364393,0.378410,0.014017,0.504016,0.454918,-0.049098,0.044177,0.025956,...,0.017454,0.082122,0.098396,0.016274,0.492778,0.572354,0.079576,0.058624,0.053996,-0.004628
4990,E01035719,-34.0,0.239919,0.369497,0.129578,0.365530,0.344392,-0.021139,0.295455,0.262243,...,-0.011999,0.162562,0.185286,0.022725,0.516755,0.583824,0.067069,0.049383,0.045588,-0.003794
4991,E01035720,-38.0,0.239750,0.345111,0.105360,0.365159,0.250847,-0.114312,0.294807,0.411864,...,-0.123813,0.161396,0.198682,0.037286,0.515625,0.485337,-0.030288,0.050000,0.096774,0.046774
4992,E01035721,-11.0,0.324357,0.439863,0.115505,0.226852,0.201224,-0.025628,0.463735,0.483550,...,0.015571,0.263651,0.265842,0.002191,0.366980,0.495814,0.128834,0.107199,0.080930,-0.026269
4993,E01035722,-13.0,0.164505,0.340288,0.175783,0.190789,0.186441,-0.004349,0.089713,0.136441,...,-0.057387,0.090232,0.106360,0.016128,0.534215,0.624576,0.090361,0.032202,0.034746,0.002543

In [72]:
df_census.to_csv("../Output/data for gentrification classification.csv", index=False)