In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Dataset/LSOA Best-fit lookup(2001-2011-2021)/LSOA_(2011)_to_LSOA_(2021)_to_Local_Authority_District_(2022)_Best_Fit_Lookup_for_EW_(V2).csv")

In [3]:
df = df[df['LAD22CD'].str.startswith('E09')]
df.drop(columns=['LAD22NMW'], inplace=True)

In [4]:
df

,ObjectId,LSOA11CD,LSOA11NM,LSOA21CD,LSOA21NM,LAD22CD,LAD22NM
0,1,E01000001,City of London 001A,E01000001,City of London 001A,E09000001,City of London
1,2,E01000002,City of London 001B,E01000002,City of London 001B,E09000001,City of London
2,3,E01000003,City of London 001C,E01000003,City of London 001C,E09000001,City of London
3,4,E01000005,City of London 001E,E01000005,City of London 001E,E09000001,City of London
4,5,E01000006,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham
...,...,...,...,...,...,...,...
32817,32818,E01033742,Greenwich 007F,E01033742,Greenwich 007F,E09000011,Greenwich
32818,32819,E01033743,Greenwich 002H,E01033743,Greenwich 002H,E09000011,Greenwich
32819,32820,E01033744,Greenwich 007G,E01033744,Greenwich 007G,E09000011,Greenwich
32820,32821,E01033745,Greenwich 002I,E01033745,Greenwich 002I,E09000011,Greenwich
32821,32822,E01033746,Greenwich 038E,E01033746,Greenwich 038E,E09000011,Greenwich

In [5]:
# Count occurrences of each LSOA code in 2001 and 2011
count_2011 = df['LSOA11CD'].value_counts()
count_2021 = df['LSOA21CD'].value_counts()

# Filter rows where both lsoa2001cd and lsoa2011cd appear only once,
# ensuring a strict one-to-one mapping (no splits or merges)
df_lsoa_U_2011_2021 = df[(df['LSOA11CD'].map(count_2011) == 1) & (df['LSOA21CD'].map(count_2021) == 1)]

# Display the final filtered dataset
df_lsoa_U_2011_2021

,ObjectId,LSOA11CD,LSOA11NM,LSOA21CD,LSOA21NM,LAD22CD,LAD22NM
0,1,E01000001,City of London 001A,E01000001,City of London 001A,E09000001,City of London
1,2,E01000002,City of London 001B,E01000002,City of London 001B,E09000001,City of London
2,3,E01000003,City of London 001C,E01000003,City of London 001C,E09000001,City of London
3,4,E01000005,City of London 001E,E01000005,City of London 001E,E09000001,City of London
4,5,E01000006,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham
...,...,...,...,...,...,...,...
32817,32818,E01033742,Greenwich 007F,E01033742,Greenwich 007F,E09000011,Greenwich
32818,32819,E01033743,Greenwich 002H,E01033743,Greenwich 002H,E09000011,Greenwich
32819,32820,E01033744,Greenwich 007G,E01033744,Greenwich 007G,E09000011,Greenwich
32820,32821,E01033745,Greenwich 002I,E01033745,Greenwich 002I,E09000011,Greenwich
32821,32822,E01033746,Greenwich 038E,E01033746,Greenwich 038E,E09000011,Greenwich

In [6]:
df_ = pd.read_excel("../Dataset/LSOA Best-fit lookup(2001-2011-2021)/2001_to_2011_OA-LSOA-MSOA-WARD-BOROUGH.xls", engine='xlrd', sheet_name='LSOA')

In [7]:
df_ = df_.iloc[:4853]

In [8]:
df_

       LSOA01CD             LSOA01NM   LSOA11CD             LSOA11NM CHGIND
0     E01000001  City of London 001A  E01000001  City of London 001A      U
1     E01000002  City of London 001B  E01000002  City of London 001B      U
2     E01000003  City of London 001C  E01000003  City of London 001C      U
3     E01000004  City of London 001D  E01032739  City of London 001F      S
4     E01000004  City of London 001D  E01032740  City of London 001G      S
...         ...                  ...        ...                  ...    ...
4848  E01004762     Westminster 011E  E01004762     Westminster 011E      U
4849  E01004763     Westminster 013B  E01004763     Westminster 013B      U
4850  E01004764     Westminster 013C  E01033595     Westminster 013E      S
4851  E01004764     Westminster 013C  E01033596     Westminster 013F      S
4852  E01004765     Westminster 013D  E01004765     Westminster 013D      U

[4853 rows x 5 columns]

In [9]:
counts_change = df_['CHGIND'].value_counts().reset_index()
counts_change.columns = ['Element', 'Count']

print(counts_change)

  Element  Count
0       U   4642
1       S    152
2       M     32
3       X     27

In [10]:
df_lsoa_U_2001_2011 = df_[df_['CHGIND'] == 'U']

In [11]:
df_lsoa_U_2001_2011

,LSOA01CD,LSOA01NM,LSOA11CD,LSOA11NM,CHGIND
0,E01000001,City of London 001A,E01000001,City of London 001A,U
1,E01000002,City of London 001B,E01000002,City of London 001B,U
2,E01000003,City of London 001C,E01000003,City of London 001C,U
5,E01000005,City of London 001E,E01000005,City of London 001E,U
6,E01000006,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,U
...,...,...,...,...,...
4846,E01004760,Westminster 014E,E01004760,Westminster 014E,U
4847,E01004761,Westminster 018D,E01004761,Westminster 018D,U
4848,E01004762,Westminster 011E,E01004762,Westminster 011E,U
4849,E01004763,Westminster 013B,E01004763,Westminster 013B,U
4852,E01004765,Westminster 013D,E01004765,Westminster 013D,U

In [12]:
df_lsoa_U_2001_2021 = pd.merge(df_lsoa_U_2001_2011, df_lsoa_U_2011_2021, left_on='LSOA11CD', right_on='LSOA11CD', how='left')

In [13]:
df_lsoa_U_2001_2021

,LSOA01CD,LSOA01NM,LSOA11CD,LSOA11NM_x,CHGIND,ObjectId,LSOA11NM_y,LSOA21CD,LSOA21NM,LAD22CD,LAD22NM
0,E01000001,City of London 001A,E01000001,City of London 001A,U,1.0,City of London 001A,E01000001,City of London 001A,E09000001,City of London
1,E01000002,City of London 001B,E01000002,City of London 001B,U,2.0,City of London 001B,E01000002,City of London 001B,E09000001,City of London
2,E01000003,City of London 001C,E01000003,City of London 001C,U,3.0,City of London 001C,E01000003,City of London 001C,E09000001,City of London
3,E01000005,City of London 001E,E01000005,City of London 001E,U,4.0,City of London 001E,E01000005,City of London 001E,E09000001,City of London
4,E01000006,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,U,5.0,Barking and Dagenham 016A,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham
...,...,...,...,...,...,...,...,...,...,...,...
4637,E01004760,Westminster 014E,E01004760,Westminster 014E,U,4590.0,Westminster 014E,E01004760,Westminster 014E,E09000033,Westminster
4638,E01004761,Westminster 018D,E01004761,Westminster 018D,U,4591.0,Westminster 018D,E01004761,Westminster 018D,E09000033,Westminster
4639,E01004762,Westminster 011E,E01004762,Westminster 011E,U,4592.0,Westminster 011E,E01004762,Westminster 011E,E09000033,Westminster
4640,E01004763,Westminster 013B,E01004763,Westminster 013B,U,4593.0,Westminster 013B,E01004763,Westminster 013B,E09000033,Westminster
4641,E01004765,Westminster 013D,E01004765,Westminster 013D,U,4594.0,Westminster 013D,E01004765,Westminster 013D,E09000033,Westminster

In [14]:
# Select the columns needed in the analysis
selected_columns = ['LSOA01CD', 'LSOA11CD', 'LSOA21CD', 'LSOA21NM', 'LAD22CD', 'LAD22NM']
df_lsoa_U_2001_2021 = df_lsoa_U_2001_2021[selected_columns]

In [15]:
df_lsoa_U_2001_2021

,LSOA01CD,LSOA11CD,LSOA21CD,LSOA21NM,LAD22CD,LAD22NM
0,E01000001,E01000001,E01000001,City of London 001A,E09000001,City of London
1,E01000002,E01000002,E01000002,City of London 001B,E09000001,City of London
2,E01000003,E01000003,E01000003,City of London 001C,E09000001,City of London
3,E01000005,E01000005,E01000005,City of London 001E,E09000001,City of London
4,E01000006,E01000006,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham
...,...,...,...,...,...,...
4637,E01004760,E01004760,E01004760,Westminster 014E,E09000033,Westminster
4638,E01004761,E01004761,E01004761,Westminster 018D,E09000033,Westminster
4639,E01004762,E01004762,E01004762,Westminster 011E,E09000033,Westminster
4640,E01004763,E01004763,E01004763,Westminster 013B,E09000033,Westminster
4641,E01004765,E01004765,E01004765,Westminster 013D,E09000033,Westminster

In [16]:
df_lsoa_U_2001_2021.to_csv('../Output/lsoa_2001_to_2021_unchnaged.csv', index=False)