In [316]:
import os
import pandas as pd

In [317]:
# Exclude the datasets used in the gentrification classification
datasets_used_in_classification = ("Education", "Ethnic", "NS-SeC", "Occupation", "Tenure")

In [318]:
# Directory containing CSV files
data_dir_2011 = "../Dataset/Census London 2011/"

merged_df_2011 = None

# Loop over all files in the directory
for filename in os.listdir(data_dir_2011):
    if filename.endswith("mapped.csv") and not filename.startswith(datasets_used_in_classification):

        filepath = os.path.join(data_dir_2011, filename)
        
        df_2011 = pd.read_csv(filepath)

        # If this is the first file, initialize merged_df
        if merged_df_2011 is None:
            merged_df_2011 = df_2011

        else:
            # Drop duplicate columns before merging
            df_2011 = df_2011[[col for col in df_2011.columns if col == 'LSOA21CD' or col not in merged_df_2011.columns]]
            # Merge on 'LSOACD21'
            merged_df_2011 = pd.merge(merged_df_2011, df_2011, on='LSOA21CD', how='outer')

merged_df_2011.columns = [merged_df_2011.columns[0]] + [col.replace('_weighted', '') for col in merged_df_2011.columns[1:]]

In [319]:
merged_df_2011

,LSOA21CD,All categories: Age,Age under 1,Age 1,Age 2,Age 3,Age 4,Age 5,Age 6,Age 7,...,All categories: Number of rooms,1 room,2 rooms,3 rooms,4 rooms,5 rooms,6 rooms,7 rooms,8 rooms,9 or more rooms
0,E01000001,1465.0,11.0,13.0,5.0,8.0,13.0,5.0,10.0,4.0,...,876.0,92.0,87.0,278.0,181.0,120.0,71.0,34.0,10.0,3.0
1,E01000002,1436.0,19.0,16.0,11.0,6.0,8.0,9.0,16.0,8.0,...,830.0,10.0,136.0,266.0,233.0,64.0,60.0,34.0,18.0,9.0
2,E01000003,1346.0,19.0,5.0,14.0,6.0,9.0,4.0,3.0,7.0,...,817.0,128.0,196.0,231.0,212.0,44.0,3.0,2.0,0.0,1.0
3,E01000005,985.0,10.0,7.0,6.0,11.0,8.0,11.0,12.0,15.0,...,467.0,43.0,89.0,142.0,109.0,68.0,12.0,3.0,0.0,1.0
4,E01000006,1703.0,30.0,35.0,43.0,33.0,13.0,24.0,29.0,23.0,...,543.0,8.0,17.0,82.0,59.0,145.0,140.0,63.0,23.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,3123.0,21.0,24.0,15.0,18.0,5.0,17.0,10.0,17.0,...,996.0,19.0,43.0,207.0,217.0,160.0,118.0,72.0,69.0,91.0
4990,E01035719,992.0,11.0,12.0,9.0,8.0,10.0,8.0,5.0,4.0,...,528.0,7.0,69.0,184.0,165.0,63.0,21.0,9.0,4.0,5.0
4991,E01035720,1122.0,13.0,14.0,11.0,10.0,11.0,9.0,6.0,5.0,...,597.0,7.0,79.0,209.0,187.0,71.0,24.0,11.0,5.0,5.0
4992,E01035721,2451.0,27.0,33.0,22.0,19.0,20.0,24.0,28.0,18.0,...,1296.0,25.0,125.0,409.0,403.0,157.0,82.0,52.0,24.0,19.0
4993,E01035722,2699.0,21.0,24.0,22.0,23.0,8.0,8.0,15.0,14.0,...,1672.0,123.0,291.0,584.0,437.0,138.0,44.0,16.0,19.0,20.0

In [320]:
merged_df_2011['Aged 4 years and under'] = merged_df_2011['Age under 1'] + merged_df_2011['Age 1'] + merged_df_2011['Age 2'] + merged_df_2011['Age 3'] + merged_df_2011['Age 4']
merged_df_2011['Aged 5 to 9 years'] = merged_df_2011['Age 5'] + merged_df_2011['Age 6'] + merged_df_2011['Age 7'] + merged_df_2011['Age 8'] + merged_df_2011['Age 9']
merged_df_2011['Aged 10 to 14 years'] = merged_df_2011['Age 10'] + merged_df_2011['Age 11'] + merged_df_2011['Age 12'] + merged_df_2011['Age 13'] + merged_df_2011['Age 14']
merged_df_2011['Aged 15 to 19 years'] = merged_df_2011['Age 15'] + merged_df_2011['Age 16'] + merged_df_2011['Age 17'] + merged_df_2011['Age 18'] + merged_df_2011['Age 19']
merged_df_2011['Aged 20 to 24 years'] = merged_df_2011['Age 20'] + merged_df_2011['Age 21'] + merged_df_2011['Age 22'] + merged_df_2011['Age 23'] + merged_df_2011['Age 24']
merged_df_2011['Aged 25 to 29 years'] = merged_df_2011['Age 25'] + merged_df_2011['Age 26'] + merged_df_2011['Age 27'] + merged_df_2011['Age 28'] + merged_df_2011['Age 29']
merged_df_2011['Aged 30 to 34 years'] = merged_df_2011['Age 30'] + merged_df_2011['Age 31'] + merged_df_2011['Age 32'] + merged_df_2011['Age 33'] + merged_df_2011['Age 34']
merged_df_2011['Aged 35 to 39 years'] = merged_df_2011['Age 35'] + merged_df_2011['Age 36'] + merged_df_2011['Age 37'] + merged_df_2011['Age 38'] + merged_df_2011['Age 39']
merged_df_2011['Aged 40 to 44 years'] = merged_df_2011['Age 40'] + merged_df_2011['Age 41'] + merged_df_2011['Age 42'] + merged_df_2011['Age 43'] + merged_df_2011['Age 44']
merged_df_2011['Aged 45 to 49 years'] = merged_df_2011['Age 45'] + merged_df_2011['Age 46'] + merged_df_2011['Age 47'] + merged_df_2011['Age 48'] + merged_df_2011['Age 49']
merged_df_2011['Aged 50 to 54 years'] = merged_df_2011['Age 50'] + merged_df_2011['Age 51'] + merged_df_2011['Age 52'] + merged_df_2011['Age 53'] + merged_df_2011['Age 54']
merged_df_2011['Aged 55 to 59 years'] = merged_df_2011['Age 55'] + merged_df_2011['Age 56'] + merged_df_2011['Age 57'] + merged_df_2011['Age 58'] + merged_df_2011['Age 59']
merged_df_2011['Aged 60 to 64 years'] = merged_df_2011['Age 60'] + merged_df_2011['Age 61'] + merged_df_2011['Age 62'] + merged_df_2011['Age 63'] + merged_df_2011['Age 64']
merged_df_2011['Aged 65 to 69 years'] = merged_df_2011['Age 65'] + merged_df_2011['Age 66'] + merged_df_2011['Age 67'] + merged_df_2011['Age 68'] + merged_df_2011['Age 69']
merged_df_2011['Aged 70 to 74 years'] = merged_df_2011['Age 70'] + merged_df_2011['Age 71'] + merged_df_2011['Age 72'] + merged_df_2011['Age 73'] + merged_df_2011['Age 74']
merged_df_2011['Aged 75 to 79 years'] = merged_df_2011['Age 75'] + merged_df_2011['Age 76'] + merged_df_2011['Age 77'] + merged_df_2011['Age 78'] + merged_df_2011['Age 79']
merged_df_2011['Aged 80 to 84 years'] = merged_df_2011['Age 80'] + merged_df_2011['Age 81'] + merged_df_2011['Age 82'] + merged_df_2011['Age 83'] + merged_df_2011['Age 84']
merged_df_2011['Aged 85 years and over'] = (merged_df_2011['Age 85'] + merged_df_2011['Age 86'] + merged_df_2011['Age 87'] + merged_df_2011['Age 88'] + merged_df_2011['Age 89'] + 
                                            merged_df_2011['Age 90'] + merged_df_2011['Age 91'] + merged_df_2011['Age 92'] + merged_df_2011['Age 93'] + merged_df_2011['Age 94'] + 
                                            merged_df_2011['Age 95'] + merged_df_2011['Age 96'] + merged_df_2011['Age 97'] + merged_df_2011['Age 98'] + merged_df_2011['Age 99'] + merged_df_2011['Age 100 and over'])

age_drop = [
 'Age under 1',
 'Age 1',
 'Age 2',
 'Age 3',
 'Age 4',
 'Age 5',
 'Age 6',
 'Age 7',
 'Age 8',
 'Age 9',
 'Age 10',
 'Age 11',
 'Age 12',
 'Age 13',
 'Age 14',
 'Age 15',
 'Age 16',
 'Age 17',
 'Age 18',
 'Age 19',
 'Age 20',
 'Age 21',
 'Age 22',
 'Age 23',
 'Age 24',
 'Age 25',
 'Age 26',
 'Age 27',
 'Age 28',
 'Age 29',
 'Age 30',
 'Age 31',
 'Age 32',
 'Age 33',
 'Age 34',
 'Age 35',
 'Age 36',
 'Age 37',
 'Age 38',
 'Age 39',
 'Age 40',
 'Age 41',
 'Age 42',
 'Age 43',
 'Age 44',
 'Age 45',
 'Age 46',
 'Age 47',
 'Age 48',
 'Age 49',
 'Age 50',
 'Age 51',
 'Age 52',
 'Age 53',
 'Age 54',
 'Age 55',
 'Age 56',
 'Age 57',
 'Age 58',
 'Age 59',
 'Age 60',
 'Age 61',
 'Age 62',
 'Age 63',
 'Age 64',
 'Age 65',
 'Age 66',
 'Age 67',
 'Age 68',
 'Age 69',
 'Age 70',
 'Age 71',
 'Age 72',
 'Age 73',
 'Age 74',
 'Age 75',
 'Age 76',
 'Age 77',
 'Age 78',
 'Age 79',
 'Age 80',
 'Age 81',
 'Age 82',
 'Age 83',
 'Age 84',
 'Age 85',
 'Age 86',
 'Age 87',
 'Age 88',
 'Age 89',
 'Age 90',
 'Age 91',
 'Age 92',
 'Age 93',
 'Age 94',
 'Age 95',
 'Age 96',
 'Age 97',
 'Age 98',
 'Age 99',
 'Age 100 and over']

merged_df_2011.drop(columns=age_drop, inplace=True)

In [321]:
merged_df_2011['4 or more bedrooms'] = merged_df_2011['4 bedrooms'] + merged_df_2011['5 or more bedrooms']
merged_df_2011.drop(columns=['4 bedrooms', '5 or more bedrooms'], inplace=True)

In [322]:
rename_household_type_2011_to_2021 = {
    'One person household': 'One-person household',
    'One person household: Aged 65 and over': 'One-person household: Aged 66 years and over',
    'One person household: Other': 'One-person household: Other',
    'One family household': 'Single family household',
    'One family only: All aged 65 and over': 'Single family household: All aged 66 years and over',
    'One family only: Married or same-sex civil partnership couple': 'Single family household: Married or civil partnership couple',
    'One family only: Married or same-sex civil partnership couple: No children': 'Single family household: Married or civil partnership couple: No children',
    'One family only: Married or same-sex civil partnership couple: Dependent children': 'Single family household: Married or civil partnership couple: Dependent children',
    'One family only: Married or same-sex civil partnership couple: All children non-dependent': 'Single family household: Married or civil partnership couple: All children non-dependent',
    'One family only: Cohabiting couple': 'Single family household: Cohabiting couple family',
    'One family only: Cohabiting couple: No children': 'Single family household: Cohabiting couple family: No children',
    'One family only: Cohabiting couple: Dependent children': 'Single family household: Cohabiting couple family: With dependent children',
    'One family only: Cohabiting couple: All children non-dependent': 'Single family household: Cohabiting couple family: All children non-dependent',
    'One family only: Lone parent': 'Single family household: Lone parent family',
    'One family only: Lone parent: Dependent children': 'Single family household: Lone parent family: With dependent children',
    'One family only: Lone parent: All children non-dependent': 'Single family household: Lone parent family: All children non-dependent',
    'Other household types': 'Other household types',
    'Other household types: With dependent children': 'Other household types: With dependent children'
}

merged_df_2011.rename(columns=rename_household_type_2011_to_2021, inplace=True)

merged_df_2011['Other household types: Other, including all full-time students and all aged 66 years and over'] = (merged_df_2011['Other household types: All full-time students'] + 
                                                                                                                   merged_df_2011['Other household types: All aged 65 and over'] + 
                                                                                                                   merged_df_2011['Other household types: Other'])

merged_df_2011.drop(columns=['Other household types: All full-time students', 'Other household types: All aged 65 and over', 'Other household types: Other'], inplace=True)

In [323]:
merged_df_2011['3 or more cars or vans in household'] = merged_df_2011['3 cars or vans in household'] + merged_df_2011['4 or more cars or vans in household']

merged_df_2011.drop(columns=['3 cars or vans in household', '4 or more cars or vans in household'], inplace=True)

In [324]:
merged_df_2011.rename(columns={'Economically inactive: Student (including full-time students)':'Economically inactive: Student'}, inplace=True)
merged_df_2011.rename(columns={'All categories: Economic activity': 'All Households'}, inplace=True)
merged_df_2011.rename(columns={'All categories: Age': 'All population'}, inplace=True)

In [325]:
merged_df_2011.drop(columns=['All categories: Hours worked',
 'Average distance (km)',
 'All categories: Car or van availability',
 'All categories: Number of rooms',
 'Total distance (km)',
 'All categories: Distance travelled to work',
 'All categories: Household composition',
 'All categories: Number of bedrooms',
 'No bedrooms',
 'Other',
 'Part-time: Total',
 'Full-time: Total',
 'sum of All cars or vans in the area'
],
inplace=True)

In [326]:
merged_df_2011.rename(columns={'Work mainly at or from home': 'Works mainly from home'}, inplace=True)

In [327]:
# Directory containing CSV files
data_dir_2021 = "../Dataset/Census London 2021/"

merged_df_2021 = None

# Loop over all files in the directory
for filename in os.listdir(data_dir_2021):
    if filename.endswith("2021.csv") and not filename.startswith(datasets_used_in_classification):

        filepath = os.path.join(data_dir_2021, filename)
        
        df_2021 = pd.read_csv(filepath)

        # If this is the first file, initialize merged_df
        if merged_df_2021 is None:
            merged_df_2021 = df_2021

        else:
            # Drop duplicate columns before merging
            df_2021 = df_2021[[col for col in df_2021.columns if col == 'LSOA21CD' or col not in merged_df_2021.columns]]
            # Merge on 'LSOACD21'
            merged_df_2021 = pd.merge(merged_df_2021, df_2021, on='LSOA21CD', how='outer')

In [328]:
merged_df_2021

,LSOA21CD,Borough,Total,Aged 4 years and under,Aged 5 to 9 years,Aged 10 to 14 years,Aged 15 to 19 years,Aged 20 to 24 years,Aged 25 to 29 years,Aged 30 to 34 years,...,4 or more bedrooms,1 room,2 rooms,3 rooms,4 rooms,5 rooms,6 rooms,7 rooms,8 rooms,9 or more rooms
0,E01000001,City of London,1473,52,34,32,23,90,159,132,...,44.0,88.0,169.0,322.0,51.0,150.0,49.0,3.0,4.0,1.0
1,E01000002,City of London,1384,33,24,22,31,100,166,134,...,52.0,97.0,237.0,288.0,64.0,60.0,67.0,3.0,0.0,7.0
2,E01000003,City of London,1613,39,32,33,23,96,187,166,...,8.0,173.0,475.0,293.0,55.0,14.0,3.0,4.0,0.0,0.0
3,E01000005,City of London,1101,52,45,35,89,118,97,118,...,8.0,59.0,131.0,158.0,118.0,12.0,2.0,0.0,0.0,1.0
4,E01000006,Barking and Dagenham,1842,153,127,110,122,124,130,174,...,128.0,6.0,90.0,62.0,61.0,304.0,20.0,6.0,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,Westminster,2568,93,97,57,673,400,152,135,...,172.0,20.0,111.0,179.0,126.0,125.0,60.0,55.0,22.0,33.0
4990,E01035719,Westminster,1270,53,57,52,49,124,162,127,...,12.0,33.0,212.0,208.0,138.0,34.0,8.0,0.0,0.0,0.0
4991,E01035720,Westminster,1218,27,68,51,58,128,162,106,...,29.0,43.0,201.0,232.0,69.0,19.0,10.0,8.0,4.0,2.0
4992,E01035721,Westminster,2326,98,93,89,99,133,206,187,...,66.0,39.0,428.0,515.0,182.0,58.0,42.0,17.0,12.0,13.0
4993,E01035722,Westminster,2015,64,41,35,51,213,308,198,...,42.0,177.0,440.0,374.0,120.0,40.0,8.0,9.0,3.0,11.0

In [329]:
merged_df_2021['Economically active: Employee: Part-time'] = (
    merged_df_2021['Economically active (excluding full-time students): In employment: Employee: Part-time'] +
    merged_df_2021['Economically active and a full-time student: In employment: Employee: Part-time']
)

merged_df_2021['Economically active: Employee: Full-time'] = (
    merged_df_2021['Economically active (excluding full-time students): In employment: Employee: Full-time'] +
    merged_df_2021['Economically active and a full-time student: In employment: Employee: Full-time']
)

merged_df_2021['Economically active: Self-employed with employees: Part-time'] = (
    merged_df_2021['Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time'] +
    merged_df_2021['Economically active and a full-time student: In employment: Self-employed with employees: Part-time']
)

merged_df_2021['Economically active: Self-employed with employees: Full-time'] = (
    merged_df_2021['Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time'] +
    merged_df_2021['Economically active and a full-time student: In employment: Self-employed with employees: Full-time']
)

merged_df_2021['Economically active: Self-employed without employees: Part-time'] = (
    merged_df_2021['Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time'] +
    merged_df_2021['Economically active and a full-time student: In employment: Self-employed without employees: Part-time']
)

merged_df_2021['Economically active: Self-employed without employees: Full-time'] = (
    merged_df_2021['Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time'] +
    merged_df_2021['Economically active and a full-time student: In employment: Self-employed without employees: Full-time']
)

merged_df_2021['Economically active: Unemployed'] = (
    merged_df_2021['Economically active (excluding full-time students): Unemployed'] +
    merged_df_2021['Economically active and a full-time student: Unemployed']
)

student_cols = [col for col in merged_df_2021.columns if col.startswith('Economically active and a full-time student')]
merged_df_2021['Economically active: Full-time student'] = merged_df_2021[student_cols].sum(axis=1)

# Economically active: Total
active_cols = [col for col in merged_df_2021.columns if col.startswith('Economically active') and 'inactive' not in col.lower()]
merged_df_2021['Economically active: Total'] = merged_df_2021[active_cols].sum(axis=1)

# Economically inactive: Total
inactive_cols = [col for col in merged_df_2021.columns if col.startswith('Economically inactive')]
merged_df_2021['Economically inactive: Total'] = merged_df_2021[inactive_cols].sum(axis=1)

eco_act_drop = [
    'Economically active (excluding full-time students)',
    'Economically active (excluding full-time students):In employment',
    'Economically active (excluding full-time students):In employment:Employee',
    'Economically active (excluding full-time students): In employment: Employee: Part-time',
    'Economically active (excluding full-time students): In employment: Employee: Full-time',
    'Economically active (excluding full-time students):In employment:Self-employed with employees',
    'Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time',
    'Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time',
    'Economically active (excluding full-time students):In employment:Self-employed without employees',
    'Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time',
    'Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time',
    'Economically active (excluding full-time students): Unemployed',
    'Economically active and a full-time student',
    'Economically active and a full-time student:In employment',
    'Economically active and a full-time student:In employment:Employee',
    'Economically active and a full-time student: In employment: Employee: Part-time',
    'Economically active and a full-time student: In employment: Employee: Full-time',
    'Economically active and a full-time student:In employment:Self-employed with employees',
    'Economically active and a full-time student: In employment: Self-employed with employees: Part-time',
    'Economically active and a full-time student: In employment: Self-employed with employees: Full-time',
    'Economically active and a full-time student:In employment:Self-employed without employees',
    'Economically active and a full-time student: In employment: Self-employed without employees: Part-time',
    'Economically active and a full-time student: In employment: Self-employed without employees: Full-time',
    'Economically active and a full-time student: Unemployed',
]

merged_df_2021.drop(columns=eco_act_drop, inplace=True)

In [330]:
merged_df_2021.drop(columns=['Works mainly at an offshore installation, in no fixed place, or outside the UK',
'Borough',
'Part-time',
'Full-time',
'Total: All usual residents aged 16 years and over in employment the week before the census',
'Total: All usual residents aged 16 years and over',
'Single family household: Other single family household: Other family composition',
'Single family household: Other single family household',
'Economically inactive'],
inplace=True)

In [331]:
merged_df_2021.rename(columns={'Total: All households': 'All Households'}, inplace=True)
merged_df_2021.rename(columns={'Total': 'All population'}, inplace=True)

In [332]:
cols_df1 = set(merged_df_2011.columns)
cols_df2 = set(merged_df_2021.columns)


unique_in_df1 = cols_df1 - cols_df2
unique_in_df2 = cols_df2 - cols_df1

print("df1 unique column：", list(unique_in_df1))
print("df2 unique column：", list(unique_in_df2))

df1 unique column： []
df2 unique column： []

In [333]:
column_order = [
'LSOA21CD',
'All population',
'All Households',
'Aged 4 years and under',
'Aged 5 to 9 years',
'Aged 10 to 14 years',
'Aged 15 to 19 years',
'Aged 20 to 24 years',
'Aged 25 to 29 years',
'Aged 30 to 34 years',
'Aged 35 to 39 years',
'Aged 40 to 44 years',
'Aged 45 to 49 years',
'Aged 50 to 54 years',
'Aged 55 to 59 years',
'Aged 60 to 64 years',
'Aged 65 to 69 years',
'Aged 70 to 74 years',
'Aged 75 to 79 years',
'Aged 80 to 84 years',
'Aged 85 years and over',
'No cars or vans in household',
'1 car or van in household',
'2 cars or vans in household',
'3 or more cars or vans in household',
'Less than 2km',
'2km to less than 5km',
'5km to less than 10km',
'10km to less than 20km',
'20km to less than 30km',
'30km to less than 40km',
'40km to less than 60km',
'60km and over',
'Works mainly from home',
'Economically inactive: Total',
'Economically inactive: Retired',
'Economically inactive: Student',
'Economically inactive: Looking after home or family',
'Economically inactive: Long-term sick or disabled',
'Economically inactive: Other',
'Economically active: Total',
'Economically active: Employee: Part-time',
'Economically active: Employee: Full-time',
'Economically active: Self-employed with employees: Part-time',
'Economically active: Self-employed with employees: Full-time',
'Economically active: Self-employed without employees: Part-time',
'Economically active: Self-employed without employees: Full-time',
'Economically active: Unemployed',
'Economically active: Full-time student',
'Part-time: 15 hours or less worked',
'Part-time: 16 to 30 hours worked',
'Full-time: 31 to 48 hours worked',
'Full-time: 49 or more hours worked',
'One-person household',
'One-person household: Aged 66 years and over',
'One-person household: Other',
'Single family household',
'Single family household: All aged 66 years and over',
'Single family household: Married or civil partnership couple',
'Single family household: Married or civil partnership couple: No children',
'Single family household: Married or civil partnership couple: Dependent children',
'Single family household: Married or civil partnership couple: All children non-dependent',
'Single family household: Cohabiting couple family',
'Single family household: Cohabiting couple family: No children',
'Single family household: Cohabiting couple family: With dependent children',
'Single family household: Cohabiting couple family: All children non-dependent',
'Single family household: Lone parent family',
'Single family household: Lone parent family: With dependent children',
'Single family household: Lone parent family: All children non-dependent',
'Other household types',
'Other household types: With dependent children',
'Other household types: Other, including all full-time students and all aged 66 years and over',
'1 bedroom',
'2 bedrooms',
'3 bedrooms',
'4 or more bedrooms',
'1 room',
'2 rooms',
'3 rooms',
'4 rooms',
'5 rooms',
'6 rooms',
'7 rooms',
'8 rooms',
'9 or more rooms'
]

In [334]:
merged_df_2011=merged_df_2011[column_order]
merged_df_2021=merged_df_2011[column_order]

In [335]:
merged_df_2011

,LSOA21CD,All population,All Households,Aged 4 years and under,Aged 5 to 9 years,Aged 10 to 14 years,Aged 15 to 19 years,Aged 20 to 24 years,Aged 25 to 29 years,Aged 30 to 34 years,...,4 or more bedrooms,1 room,2 rooms,3 rooms,4 rooms,5 rooms,6 rooms,7 rooms,8 rooms,9 or more rooms
0,E01000001,1465.0,1221.0,50.0,33.0,26.0,19.0,63.0,140.0,151.0,...,43.0,92.0,87.0,278.0,181.0,120.0,71.0,34.0,10.0,3.0
1,E01000002,1436.0,1196.0,60.0,46.0,30.0,28.0,40.0,92.0,112.0,...,65.0,10.0,136.0,266.0,233.0,64.0,60.0,34.0,18.0,9.0
2,E01000003,1346.0,1102.0,53.0,22.0,24.0,72.0,77.0,144.0,135.0,...,3.0,128.0,196.0,231.0,212.0,44.0,3.0,2.0,0.0,1.0
3,E01000005,985.0,773.0,42.0,60.0,49.0,48.0,97.0,122.0,80.0,...,7.0,43.0,89.0,142.0,109.0,68.0,12.0,3.0,0.0,1.0
4,E01000006,1703.0,1251.0,154.0,122.0,100.0,83.0,129.0,216.0,189.0,...,92.0,8.0,17.0,82.0,59.0,145.0,140.0,63.0,23.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,3123.0,2752.0,83.0,69.0,76.0,846.0,496.0,253.0,201.0,...,205.0,19.0,43.0,207.0,217.0,160.0,118.0,72.0,69.0,91.0
4990,E01035719,992.0,812.0,50.0,33.0,38.0,32.0,68.0,112.0,106.0,...,15.0,7.0,69.0,184.0,165.0,63.0,21.0,9.0,4.0,5.0
4991,E01035720,1122.0,917.0,59.0,37.0,42.0,37.0,75.0,125.0,119.0,...,16.0,7.0,79.0,209.0,187.0,71.0,24.0,11.0,5.0,5.0
4992,E01035721,2451.0,1923.0,121.0,115.0,102.0,63.0,171.0,238.0,241.0,...,77.0,25.0,125.0,409.0,403.0,157.0,82.0,52.0,24.0,19.0
4993,E01035722,2699.0,2283.0,98.0,53.0,36.0,39.0,187.0,427.0,379.0,...,38.0,123.0,291.0,584.0,437.0,138.0,44.0,16.0,19.0,20.0

In [336]:
merged_df_2021

,LSOA21CD,All population,All Households,Aged 4 years and under,Aged 5 to 9 years,Aged 10 to 14 years,Aged 15 to 19 years,Aged 20 to 24 years,Aged 25 to 29 years,Aged 30 to 34 years,...,4 or more bedrooms,1 room,2 rooms,3 rooms,4 rooms,5 rooms,6 rooms,7 rooms,8 rooms,9 or more rooms
0,E01000001,1465.0,1221.0,50.0,33.0,26.0,19.0,63.0,140.0,151.0,...,43.0,92.0,87.0,278.0,181.0,120.0,71.0,34.0,10.0,3.0
1,E01000002,1436.0,1196.0,60.0,46.0,30.0,28.0,40.0,92.0,112.0,...,65.0,10.0,136.0,266.0,233.0,64.0,60.0,34.0,18.0,9.0
2,E01000003,1346.0,1102.0,53.0,22.0,24.0,72.0,77.0,144.0,135.0,...,3.0,128.0,196.0,231.0,212.0,44.0,3.0,2.0,0.0,1.0
3,E01000005,985.0,773.0,42.0,60.0,49.0,48.0,97.0,122.0,80.0,...,7.0,43.0,89.0,142.0,109.0,68.0,12.0,3.0,0.0,1.0
4,E01000006,1703.0,1251.0,154.0,122.0,100.0,83.0,129.0,216.0,189.0,...,92.0,8.0,17.0,82.0,59.0,145.0,140.0,63.0,23.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,3123.0,2752.0,83.0,69.0,76.0,846.0,496.0,253.0,201.0,...,205.0,19.0,43.0,207.0,217.0,160.0,118.0,72.0,69.0,91.0
4990,E01035719,992.0,812.0,50.0,33.0,38.0,32.0,68.0,112.0,106.0,...,15.0,7.0,69.0,184.0,165.0,63.0,21.0,9.0,4.0,5.0
4991,E01035720,1122.0,917.0,59.0,37.0,42.0,37.0,75.0,125.0,119.0,...,16.0,7.0,79.0,209.0,187.0,71.0,24.0,11.0,5.0,5.0
4992,E01035721,2451.0,1923.0,121.0,115.0,102.0,63.0,171.0,238.0,241.0,...,77.0,25.0,125.0,409.0,403.0,157.0,82.0,52.0,24.0,19.0
4993,E01035722,2699.0,2283.0,98.0,53.0,36.0,39.0,187.0,427.0,379.0,...,38.0,123.0,291.0,584.0,437.0,138.0,44.0,16.0,19.0,20.0

In [337]:
from sklearn.preprocessing import StandardScaler

numeric_cols_2011 = merged_df_2011.columns.drop("LSOA21CD")
numeric_cols_2021 = merged_df_2021.columns.drop("LSOA21CD")

scaler = StandardScaler()
df_scaled_2011 = pd.DataFrame()
df_scaled_2011[numeric_cols_2011] = scaler.fit_transform(merged_df_2011[numeric_cols_2011])
df_scaled_2011.insert(0, "LSOA21CD", merged_df_2011['LSOA21CD'])

df_scaled_2021 = pd.DataFrame()
df_scaled_2021[numeric_cols_2021] = scaler.fit_transform(merged_df_2021[numeric_cols_2021])
df_scaled_2021.insert(0, "LSOA21CD", merged_df_2021['LSOA21CD'])

In [342]:
df_scaled_2011["LSOA21CD"] = df_scaled_2011["LSOA21CD"].astype(str)

df_scaled_2011.sort_values(by="LSOA21CD", inplace=True)
df_scaled_2011.reset_index(drop=True, inplace=True)

df_scaled_2021["LSOA21CD"] = df_scaled_2021["LSOA21CD"].astype(str)

df_scaled_2021.sort_values(by="LSOA21CD", inplace=True)
df_scaled_2021.reset_index(drop=True, inplace=True)

In [343]:
df_scaled_2011.to_csv("../Output/Pred Input/SES_2011.csv", index=False)
df_scaled_2021.to_csv("../Output/Pred Input/SES_2021.csv", index=False)