In [97]:
import os
import pandas as pd

In [98]:
# Exclude the datasets used in the gentrification classification
datasets_used_in_classification = ("Education", "Ethnic", "NS-SeC", "Occupation", "Tenure")

In [99]:
# Directory containing CSV files
data_dir_2011 = "../Dataset/Census London 2011/"

merged_df_2011 = None

# Loop over all files in the directory
for filename in os.listdir(data_dir_2011):
    if filename.endswith("mapped.csv") and not filename.startswith(datasets_used_in_classification):

        filepath = os.path.join(data_dir_2011, filename)
        
        df = pd.read_csv(filepath)

        # If this is the first file, initialize merged_df
        if merged_df_2011 is None:
            merged_df_2011 = df

        else:
            # Drop duplicate columns before merging
            df = df[[col for col in df.columns if col == 'LSOA21CD' or col not in merged_df_2011.columns]]
            # Merge on 'LSOACD21'
            merged_df_2011 = pd.merge(merged_df_2011, df, on='LSOA21CD', how='outer')

merged_df_2011.columns = [merged_df_2011.columns[0]] + [col.replace('_weighted', '') for col in merged_df_2011.columns[1:]]

In [100]:
merged_df_2011

,LSOA21CD,All categories: Age,Age under 1,Age 1,Age 2,Age 3,Age 4,Age 5,Age 6,Age 7,Age 8,Age 9,Age 10,Age 11,Age 12,Age 13,Age 14,Age 15,Age 16,Age 17,Age 18,Age 19,Age 20,Age 21,Age 22,Age 23,Age 24,Age 25,Age 26,Age 27,Age 28,Age 29,Age 30,Age 31,Age 32,Age 33,Age 34,Age 35,Age 36,Age 37,Age 38,Age 39,Age 40,Age 41,Age 42,Age 43,Age 44,Age 45,Age 46,Age 47,Age 48,Age 49,Age 50,Age 51,Age 52,Age 53,Age 54,Age 55,Age 56,Age 57,Age 58,Age 59,Age 60,Age 61,Age 62,Age 63,Age 64,Age 65,Age 66,Age 67,Age 68,Age 69,Age 70,Age 71,Age 72,Age 73,Age 74,Age 75,Age 76,Age 77,Age 78,Age 79,Age 80,Age 81,Age 82,Age 83,Age 84,Age 85,Age 86,Age 87,Age 88,Age 89,Age 90,Age 91,Age 92,Age 93,Age 94,Age 95,Age 96,Age 97,Age 98,Age 99,Age 100 and over,All categories: Car or van availability,No cars or vans in household,1 car or van in household,2 cars or vans in household,3 cars or vans in household,4 or more cars or vans in household,sum of All cars or vans in the area,All categories: Distance travelled to work,Less than 2km,2km to less than 5km,5km to less than 10km,10km to less than 20km,20km to less than 30km,30km to less than 40km,40km to less than 60km,60km and over,Work mainly at or from home,Other,Total distance (km),Average distance (km),All categories: Economic activity,Economically active: Total,Economically active: Employee: Part-time,Economically active: Employee: Full-time,Economically active: Self-employed with employees: Part-time,Economically active: Self-employed with employees: Full-time,Economically active: Self-employed without employees: Part-time,Economically active: Self-employed without employees: Full-time,Economically active: Unemployed,Economically active: Full-time student,Economically inactive: Total,Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,All categories: Hours worked,Part-time: Total,Part-time: 15 hours or less worked,Part-time: 16 to 30 hours worked,Full-time: Total,Full-time: 31 to 48 hours worked,Full-time: 49 or more hours worked,All categories: Household composition,One person household,One person household: Aged 65 and over,One person household: Other,One family household,One family only: All aged 65 and over,One family only: Married or same-sex civil partnership couple,One family only: Married or same-sex civil partnership couple: No children,One family only: Married or same-sex civil partnership couple: Dependent children,One family only: Married or same-sex civil partnership couple: All children non-dependent,One family only: Cohabiting couple,One family only: Cohabiting couple: No children,One family only: Cohabiting couple: Dependent children,One family only: Cohabiting couple: All children non-dependent,One family only: Lone parent,One family only: Lone parent: Dependent children,One family only: Lone parent: All children non-dependent,Other household types,Other household types: With dependent children,Other household types: All full-time students,Other household types: All aged 65 and over,Other household types: Other,All categories: Number of bedrooms,No bedrooms,1 bedroom,2 bedrooms,3 bedrooms,4 bedrooms,5 or more bedrooms,All categories: Number of rooms,1 room,2 rooms,3 rooms,4 rooms,5 rooms,6 rooms,7 rooms,8 rooms,9 or more rooms
0,E01000001,1465.0,11.0,13.0,5.0,8.0,13.0,5.0,10.0,4.0,10.0,4.0,4.0,6.0,3.0,10.0,3.0,6.0,3.0,4.0,2.0,4.0,9.0,4.0,22.0,18.0,10.0,31.0,30.0,21.0,35.0,23.0,25.0,45.0,26.0,27.0,28.0,29.0,32.0,19.0,18.0,23.0,20.0,20.0,26.0,26.0,15.0,26.0,18.0,23.0,25.0,27.0,23.0,24.0,22.0,18.0,15.0,25.0,26.0,22.0,27.0,38.0,26.0,20.0,19.0,38.0,25.0,20.0,17.0,14.0,15.0,6.0,16.0,13.0,18.0,7.0,13.0,11.0,13.0,8.0,14.0,14.0,12.0,6.0,10.0,9.0,6.0,6.0,5.0,5.0,1.0,2.0,6.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,876.0,519.0,285.0,53.0,15.0,4.0,452.0,926.0,452.0,152.0,83.0,23.0,3.0,7.0,3.0,10.0,145.0,48.0,4428.0,6.0,1221.0,964.0,64.0,610.0,4.0,65.0,66.0,105.0,34.0,16.0,257.0,152.0,45.0,35.0,10.0,15.0,926.0,142.0,55.0,87.0,784.0,424.0,360.0,876.0,453.0,120.0,333.0,358.0,51.0,212.0,136.0,60.0,16.0,72.0,65.0,7.0,0.0,23.0,9.0,14.0,65.0,4.0,3.0,0.0,58.0,876.0,12.0,416.0,250.0,155.0,41.0,2.0,876.0,92.0,87.0,278.0,181.0,120.0,71.0,34.0,10.0,3.0
1,E01000002,1436.0,19.0,16.0,11.0,6.0,8.0,9.0,16.0,8.0,8.0,5.0,4.0,5.0,6.0,13.0,2.0,7.0,9.0,2.0,6.0,4.0,4.0,6.0,12.0,10.0,8.0,13.0,15.0,24.0,22.0,18.0,23.0,26.0,14.0,27.0,22.0,22.0,26.0,14.0,29.0,34.0,33.0,25.0,39.0,34.0,25.0,30.0,33.0,18.0,23.0,26.0,30.0,20.0,25.0,32.0,24.0,22.0,22.0,19.0,17.0,22.0,17.0,25.0,25.0,22.0,26.0,18.0,22.0,22.0,18.0,14.0,16.0,20.0,17.0,17.0,8.0,13.0,7.0,5.0,5.0,8.0,5.0,9.0,6.0,4.0,2.0,6.0,5.0,2.0,1.0,4.0,6.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,0.0,0.0,0.0,830.0,481.0,293.0,38.0,13.0,5.0,441.0,910.0,392.0,187.0,78.0,21.0,6.0,3.0,2.0,15.0,149.0,57.0,3779.0,5.0,1196.0,926.0,66.0,586.0,12.0,59.0,53.0,119.0,16.0,15.0,270.0,171.0,48.0,28.0,6.0,17.0,910.0,142.0,62.0,80.0,768.0,443.0,325.0,830.0,418.0,122.0,296.0,363.0,39.0,207.0,129.0,66.0,12.0,95.0,74.0,20.0,1.0,22.0,13.0,9.0,49.0,7.0,2.0,6.0,34.0,830.0,2.0,402.0,274.0,87.0,62.0,3.0,830.0,10.0,136.0,266.0,233.0,64.0,60.0,34.0,18.0,9.0
2,E01000003,1346.0,19.0,5.0,14.0,6.0,9.0,4.0,3.0,7.0,6.0,2.0,8.0,4.0,3.0,5.0,4.0,5.0,10.0,23.0,17.0,17.0,15.0,11.0,13.0,18.0,20.0,17.0,28.0,27.0,37.0,35.0,23.0,27.0,24.0,33.0,28.0,17.0,24.0,23.0,26.0,25.0,31.0,13.0,27.0,26.0,15.0,22.0,21.0,17.0,22.0,25.0,13.0,14.0,16.0,19.0,17.0,17.0,19.0,16.0,12.0,14.0,13.0,21.0,13.0,14.0,13.0,19.0,11.0,8.0,17.0,15.0,9.0,10.0,10.0,11.0,4.0,11.0,8.0,7.0,10.0,7.0,7.0,8.0,11.0,20.0,12.0,11.0,5.0,4.0,4.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,817.0,655.0,148.0,11.0,2.0,1.0,180.0,764.0,349.0,175.0,57.0,25.0,5.0,1.0,0.0,17.0,79.0,56.0,4537.0,7.0,1102.0,822.0,84.0,467.0,5.0,37.0,41.0,106.0,39.0,43.0,280.0,117.0,89.0,17.0,41.0,16.0,764.0,143.0,39.0,104.0,621.0,414.0,207.0,817.0,507.0,164.0,343.0,256.0,24.0,105.0,61.0,36.0,8.0,78.0,60.0,15.0,3.0,49.0,33.0,16.0,54.0,5.0,6.0,3.0,40.0,817.0,35.0,501.0,232.0,46.0,1.0,2.0,817.0,128.0,196.0,231.0,212.0,44.0,3.0,2.0,0.0,1.0
3,E01000005,985.0,10.0,7.0,6.0,11.0,8.0,11.0,12.0,15.0,12.0,10.0,10.0,8.0,11.0,8.0,12.0,13.0,7.0,11.0,10.0,7.0,18.0,9.0,19.0,25.0,26.0,21.0,18.0,25.0,27.0,31.0,15.0,19.0,14.0,16.0,16.0,8.0,15.0,11.0,11.0,7.0,14.0,14.0,21.0,21.0,10.0,16.0,12.0,21.0,12.0,15.0,16.0,10.0,7.0,14.0,9.0,6.0,18.0,14.0,11.0,4.0,6.0,8.0,9.0,12.0,8.0,2.0,14.0,8.0,5.0,7.0,6.0,9.0,11.0,4.0,13.0,11.0,4.0,3.0,6.0,4.0,1.0,2.0,3.0,2.0,1.0,2.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,467.0,356.0,100.0,9.0,2.0,0.0,124.0,476.0,152.0,135.0,57.0,33.0,3.0,6.0,4.0,8.0,35.0,43.0,3355.0,8.0,773.0,530.0,81.0,323.0,4.0,12.0,10.0,25.0,46.0,29.0,243.0,74.0,53.0,44.0,48.0,24.0,476.0,114.0,38.0,76.0,362.0,271.0,91.0,467.0,228.0,61.0,167.0,172.0,8.0,88.0,27.0,49.0,12.0,32.0,19.0,12.0,1.0,44.0,28.0,16.0,67.0,15.0,5.0,7.0,40.0,467.0,10.0,241.0,130.0,79.0,4.0,3.0,467.0,43.0,89.0,142.0,109.0,68.0,12.0,3.0,0.0,1.0
4,E01000006,1703.0,30.0,35.0,43.0,33.0,13.0,24.0,29.0,23.0,19.0,27.0,15.0,22.0,20.0,22.0,21.0,18.0,18.0,16.0,16.0,15.0,15.0,19.0,30.0,39.0,26.0,50.0,35.0,41.0,43.0,47.0,41.0,43.0,35.0,30.0,40.0,31.0,28.0,44.0,28.0,25.0,27.0,31.0,25.0,18.0,22.0,24.0,16.0,14.0,14.0,19.0,19.0,25.0,18.0,11.0,15.0,13.0,12.0,17.0,11.0,15.0,11.0,10.0,15.0,9.0,10.0,14.0,6.0,4.0,8.0,6.0,5.0,5.0,9.0,12.0,6.0,6.0,5.0,5.0,5.0,2.0,2.0,5.0,5.0,3.0,5.0,2.0,5.0,1.0,0.0,1.0,3.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,543.0,186.0,249.0,87.0,14.0,7.0,496.0,781.0,90.0,86.0,121.0,229.0,29.0,10.0,8.0,18.0,61.0,129.0,8880.0,15.0,1251.0,874.0,158.0,407.0,11.0,28.0,40.0,89.0,83.0,58.0,377.0,72.0,117.0,105.0,46.0,37.0,781.0,243.0,73.0,170.0,538.0,448.0,90.0,543.0,97.0,24.0,73.0,311.0,19.0,203.0,50.0,122.0,31.0,35.0,15.0,17.0,3.0,54.0,33.0,21.0,135.0,56.0,6.0,5.0,68.0,543.0,0.0,86.0,72.0,293.0,67.0,25.0,543.0,8.0,17.0,82.0,59.0,145.0,140.0,63.0,23.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,3123.0,21.0,24.0,15.0,18.0,5.0,17.0,10.0,17.0,13.0,12.0,11.0,19.0,21.0,11.0,14.0,17.0,6.0,15.0,276.0,532.0,217.0,120.0,70.0,42.0,47.0,63.0,62.0,43.0,39.0,46.0,50.0,50.0,40.0,30.0,31.0,53.0,30.0,31.0,30.0,17.0,29.0,27.0,46.0,38.0,38.0,27.0,24.0,26.0,38.0,21.0,35.0,24.0,14.0,27.0,25.0,16.0,17.0,22.0,29.0,18.0,27.0,12.0,25.0,27.0,22.0,21.0,21.0,18.0,21.0,8.0,8.0,20.0,12.0,16.0,13.0,8.0,6.0,11.0,8.0,13.0,12.0,10.0,9.0,6.0,10.0,8.0,4.0,6.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,996.0,462.0,381.0,112.0,29.0,12.0,752.0,1177.0,284.0,240.0,170.0,53.0,7.0,13.0,4.0,23.0,302.0,81.0,7764.0,20.0,2752.0,1249.0,84.0,731.0,12.0,101.0,56.0,115.0,42.0,108.0,1503.0,111.0,1134.0,125.0,20.0,113.0,1177.0,218.0,116.0,102.0,959.0,402.0,557.0,996.0,479.0,95.0,384.0,417.0,48.0,261.0,135.0,102.0,24.0,58.0,53.0,5.0,0.0,50.0,24.0,26.0,100.0,15.0,16.0,0.0,69.0,996.0,4.0,242.0,321.0,224.0,141.0,64.0,996.0,19.0,43.0,207.0,217.0,160.0,118.0,72.0,69.0,91.0
4990,E01035719,992.0,11.0,12.0,9.0,8.0,10.0,8.0,5.0,4.0,8.0,8.0,9.0,7.0,7.0,6.0,9.0,6.0,4.0,5.0,8.0,9.0,9.0,7.0,15.0,17.0,20.0,23.0,20.0,22.0,20.0,27.0,25.0,23.0,20.0,21.0,17.0,15.0,17.0,20.0,22.0,16.0,20.0,15.0,14.0,14.0,18.0,13.0,18.0,15.0,14.0,16.0,9.0,23.0,12.0,16.0,15.0,12.0,11.0,8.0,11.0,10.0,10.0,6.0,12.0,11.0,12.0,12.0,13.0,5.0,8.0,7.0,7.0,5.0,6.0,6.0,8.0,4.0,1.0,6.0,3.0,6.0,4.0,2.0,4.0,2.0,5.0,2.0,3.0,1.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,528.0,323.0,175.0,27.0,1.0,1.0,238.0,567.0,132.0,212.0,69.0,22.0,5.0,6.0,4.0,11.0,65.0,41.0,4300.0,4.0,812.0,603.0,57.0,396.0,4.0,22.0,29.0,43.0,34.0,18.0,208.0,65.0,46.0,37.0,33.0,28.0,567.0,101.0,32.0,69.0,466.0,291.0,175.0,528.0,238.0,59.0,180.0,227.0,16.0,121.0,64.0,47.0,10.0,44.0,36.0,7.0,1.0,46.0,26.0,19.0,63.0,6.0,4.0,2.0,51.0,528.0,3.0,209.0,214.0,87.0,14.0,1.0,528.0,7.0,69.0,184.0,165.0,63.0,21.0,9.0,4.0,5.0
4991,E01035720,1122.0,13.0,14.0,11.0,10.0,11.0,9.0,6.0,5.0,8.0,9.0,10.0,8.0,8.0,6.0,10.0,6.0,5.0,6.0,9.0,11.0,10.0,7.0,16.0,20.0,22.0,26.0,22.0,24.0,22.0,31.0,29.0,26.0,22.0,23.0,19.0,18.0,20.0,22.0,24.0,19.0,23.0,16.0,16.0,16.0,21.0,14.0,21.0,17.0,16.0,19.0,10.0,25.0,14.0,19.0,16.0,13.0,12.0,9.0,12.0,11.0,12.0,6.0,13.0,12.0,14.0,13.0,14.0,5.0,8.0,8.0,8.0,5.0,7.0,7.0,10.0,5.0,2.0,6.0,3.0,7.0,5.0,2.0,4.0,2.0,6.0,2.0,3.0,2.0,2.0,3.0,1.0,2.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,597.0,366.0,198.0,30.0,2.0,2.0,270.0,640.0,149.0,240.0,79.0,25.0,6.0,6.0,4.0,12.0,73.0,46.0,4860.0,5.0,917.0,682.0,65.0,448.0,4.0,25.0,33.0,49.0,38.0,20.0,236.0,73.0,52.0,41.0,37.0,32.0,640.0,114.0,37.0,77.0,526.0,329.0,197.0,597.0,270.0,66.0,203.0,256.0,18.0,137.0,72.0,54.0,11.0,50.0,41.0,8.0,1.0,51.0,30.0,22.0,71.0,6.0,4.0,3.0,58.0,597.0,3.0,237.0,242.0,99.0,15.0,1.0,597.0,7.0,79.0,209.0,187.0,71.0,24.0,11.0,5.0,5.0
4992,E01035721,2451.0,27.0,33.0,22.0,19.0,20.0,24.0,28.0,18.0,19.0,26.0,16.0,28.0,23.0,19.0,16.0,15.0,9.0,9.0,15.0,15.0,22.0,25.0,31.0,45.0,48.0,28.0,47.0,61.0,55.0,47.0,48.0,38.0,58.0,50.0,47.0,44.0,35.0,41.0,43.0,45.0,35.0,42.0,36.0,39.0,30.0,38.0,39.0,40.0,41.0,29.0,38.0,32.0,34.0,30.0,31.0,28.0,22.0,28.0,30.0,28.0,16.0,22.0,28.0,37.0,22.0,28.0,30.0,24.0,27.0,17.0,26.0,14.0,23.0,16.0,17.0,16.0,9.0,12.0,20.0,15.0,13.0,6.0,21.0,13.0,3.0,10.0,6.0,8.0,6.0,6.0,2.0,2.0,4.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1296.0,811.0,393.0,72.0,13.0,7.0,609.0,1278.0,269.0,407.0,223.0,49.0,10.0,7.0,6.0,16.0,177.0,114.0,6319.0,13.0,1923.0,1390.0,186.0,756.0,21.0,61.0,78.0,140.0,96.0,52.0,533.0,159.0,90.0,102.0,112.0,70.0,1278.0,305.0,110.0,195.0,973.0,675.0,298.0,1296.0,652.0,194.0,458.0,491.0,41.0,236.0,102.0,99.0,35.0,94.0,83.0,11.0,0.0,120.0,76.0,44.0,153.0,28.0,3.0,3.0,119.0,1296.0,9.0,525.0,482.0,203.0,64.0,13.0,1296.0,25.0,125.0,409.0,403.0,157.0,82.0,52.0,24.0,19.0
4993,E01035722,2699.0,21.0,24.0,22.0,23.0,8.0,8.0,15.0,14.0,7.0,9.0,6.0,9.0,7.0,3.0,11.0,7.0,7.0,4.0,9.0,12.0,17.0,22.0,50.0,44.0,54.0,68.0,97.0,85.0,85.0,92.0,77.0,86.0,66.0,71.0,79.0,49.0,58.0,62.0,51.0,48.0,46.0,43.0,48.0,37.0,34.0,39.0,41.0,34.0,39.0,27.0,31.0,38.0,23.0,30.0,29.0,28.0,26.0,23.0,23.0,20.0,20.0,29.0,26.0,24.0,24.0,22.0,26.0,19.0,24.0,23.0,23.0,17.0,21.0,19.0,14.0,19.0,20.0,13.0,14.0,12.0,14.0,19.0,14.0,10.0,12.0,10.0,15.0,7.0,8.0,6.0,1.0,8.0,1.0,9.0,0.0,1.0,1.0,3.0,4.0,0.0,1.0,1672.0,1064.0,526.0,68.0,11.0,3.0,707.0,1739.0,312.0,742.0,247.0,47.0,16.0,17.0,11.0,33.0,217.0,97.0,12437.0,17.0,2283.0,1813.0,120.0,1219.0,6.0,80.0,101.0,174.0,63.0,50.0,470.0,163.0,148.0,47.0,59.0,53.0,1739.0,249.0,78.0,171.0,1490.0,876.0,614.0,1672.0,992.0,233.0,759.0,488.0,46.0,216.0,132.0,74.0,10.0,177.0,165.0,11.0,1.0,49.0,23.0,26.0,192.0,15.0,19.0,8.0,150.0,1672.0,18.0,942.0,542.0,132.0,22.0,16.0,1672.0,123.0,291.0,584.0,437.0,138.0,44.0,16.0,19.0,20.0

In [101]:
list(merged_df_2011.columns)

['LSOA21CD',
 'All categories: Age',
 'Age under 1',
 'Age 1',
 'Age 2',
 'Age 3',
 'Age 4',
 'Age 5',
 'Age 6',
 'Age 7',
 'Age 8',
 'Age 9',
 'Age 10',
 'Age 11',
 'Age 12',
 'Age 13',
 'Age 14',
 'Age 15',
 'Age 16',
 'Age 17',
 'Age 18',
 'Age 19',
 'Age 20',
 'Age 21',
 'Age 22',
 'Age 23',
 'Age 24',
 'Age 25',
 'Age 26',
 'Age 27',
 'Age 28',
 'Age 29',
 'Age 30',
 'Age 31',
 'Age 32',
 'Age 33',
 'Age 34',
 'Age 35',
 'Age 36',
 'Age 37',
 'Age 38',
 'Age 39',
 'Age 40',
 'Age 41',
 'Age 42',
 'Age 43',
 'Age 44',
 'Age 45',
 'Age 46',
 'Age 47',
 'Age 48',
 'Age 49',
 'Age 50',
 'Age 51',
 'Age 52',
 'Age 53',
 'Age 54',
 'Age 55',
 'Age 56',
 'Age 57',
 'Age 58',
 'Age 59',
 'Age 60',
 'Age 61',
 'Age 62',
 'Age 63',
 'Age 64',
 'Age 65',
 'Age 66',
 'Age 67',
 'Age 68',
 'Age 69',
 'Age 70',
 'Age 71',
 'Age 72',
 'Age 73',
 'Age 74',
 'Age 75',
 'Age 76',
 'Age 77',
 'Age 78',
 'Age 79',
 'Age 80',
 'Age 81',
 'Age 82',
 'Age 83',
 'Age 84',
 'Age 85',
 'Age 86',
 'Age 87',
 'Age 88',
 'Age 89',
 'Age 90',
 'Age 91',
 'Age 92',
 'Age 93',
 'Age 94',
 'Age 95',
 'Age 96',
 'Age 97',
 'Age 98',
 'Age 99',
 'Age 100 and over',
 'All categories: Car or van availability',
 'No cars or vans in household',
 '1 car or van in household',
 '2 cars or vans in household',
 '3 cars or vans in household',
 '4 or more cars or vans in household',
 'sum of All cars or vans in the area',
 'All categories: Distance travelled to work',
 'Less than 2km',
 '2km to less than 5km',
 '5km to less than 10km',
 '10km to less than 20km',
 '20km to less than 30km',
 '30km to less than 40km',
 '40km to less than 60km',
 '60km and over',
 'Work mainly at or from home',
 'Other',
 'Total distance (km)',
 'Average distance (km)',
 'All categories: Economic activity',
 'Economically active: Total',
 'Economically active: Employee: Part-time',
 'Economically active: Employee: Full-time',
 'Economically active: Self-employed with employees: Part-time',
 'Economically active: Self-employed with employees: Full-time',
 'Economically active: Self-employed without employees: Part-time',
 'Economically active: Self-employed without employees: Full-time',
 'Economically active: Unemployed',
 'Economically active: Full-time student',
 'Economically inactive: Total',
 'Economically inactive: Retired',
 'Economically inactive: Student (including full-time students)',
 'Economically inactive: Looking after home or family',
 'Economically inactive: Long-term sick or disabled',
 'Economically inactive: Other',
 'All categories: Hours worked',
 'Part-time: Total',
 'Part-time: 15 hours or less worked',
 'Part-time: 16 to 30 hours worked',
 'Full-time: Total',
 'Full-time: 31 to 48 hours worked',
 'Full-time: 49 or more hours worked',
 'All categories: Household composition',
 'One person household',
 'One person household: Aged 65 and over',
 'One person household: Other',
 'One family household',
 'One family only: All aged 65 and over',
 'One family only: Married or same-sex civil partnership couple',
 'One family only: Married or same-sex civil partnership couple: No children',
 'One family only: Married or same-sex civil partnership couple: Dependent children',
 'One family only: Married or same-sex civil partnership couple: All children non-dependent',
 'One family only: Cohabiting couple',
 'One family only: Cohabiting couple: No children',
 'One family only: Cohabiting couple: Dependent children',
 'One family only: Cohabiting couple: All children non-dependent',
 'One family only: Lone parent',
 'One family only: Lone parent: Dependent children',
 'One family only: Lone parent: All children non-dependent',
 'Other household types',
 'Other household types: With dependent children',
 'Other household types: All full-time students',
 'Other household types: All aged 65 and over',
 'Other household types: Other',
 'All categories: Number of bedrooms',
 'No bedrooms',
 '1 bedroom',
 '2 bedrooms',
 '3 bedrooms',
 '4 bedrooms',
 '5 or more bedrooms',
 'All categories: Number of rooms',
 '1 room',
 '2 rooms',
 '3 rooms',
 '4 rooms',
 '5 rooms',
 '6 rooms',
 '7 rooms',
 '8 rooms',
 '9 or more rooms']

In [102]:
# Directory containing CSV files
data_dir_2021 = "../Dataset/Census London 2021/"

merged_df_2021 = None

# Loop over all files in the directory
for filename in os.listdir(data_dir_2021):
    if filename.endswith("2021.csv") and not filename.startswith(datasets_used_in_classification):

        filepath = os.path.join(data_dir_2021, filename)
        
        df = pd.read_csv(filepath)

        # If this is the first file, initialize merged_df
        if merged_df_2021 is None:
            merged_df_2021 = df

        else:
            # Drop duplicate columns before merging
            df = df[[col for col in df.columns if col == 'LSOA21CD' or col not in merged_df_2021.columns]]
            # Merge on 'LSOACD21'
            merged_df_2021 = pd.merge(merged_df_2021, df, on='LSOA21CD', how='outer')

In [103]:
merged_df_2021

,LSOA21CD,Borough,Total,Aged 4 years and under,Aged 5 to 9 years,Aged 10 to 14 years,Aged 15 to 19 years,Aged 20 to 24 years,Aged 25 to 29 years,Aged 30 to 34 years,Aged 35 to 39 years,Aged 40 to 44 years,Aged 45 to 49 years,Aged 50 to 54 years,Aged 55 to 59 years,Aged 60 to 64 years,Aged 65 to 69 years,Aged 70 to 74 years,Aged 75 to 79 years,Aged 80 to 84 years,Aged 85 years and over,Total: All households,No cars or vans in household,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,Total: All usual residents aged 16 years and over in employment the week before the census,Less than 2km,2km to less than 5km,5km to less than 10km,10km to less than 20km,20km to less than 30km,30km to less than 40km,40km to less than 60km,60km and over,Works mainly from home,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Total: All usual residents aged 16 years and over,Economically active (excluding full-time students),Economically active (excluding full-time students):In employment,Economically active (excluding full-time students):In employment:Employee,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students):In employment:Self-employed with employees,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students):In employment:Self-employed without employees,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student,Economically active and a full-time student:In employment,Economically active and a full-time student:In employment:Employee,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student:In employment:Self-employed with employees,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student:In employment:Self-employed without employees,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: Unemployed,Economically inactive,Economically inactive: Retired,Economically inactive: Student,Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Part-time,Part-time: 15 hours or less worked,Part-time: 16 to 30 hours worked,Full-time,Full-time: 31 to 48 hours worked,Full-time: 49 or more hours worked,One-person household,One-person household: Aged 66 years and over,One-person household: Other,Single family household,Single family household: All aged 66 years and over,Single family household: Married or civil partnership couple,Single family household: Married or civil partnership couple: No children,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Cohabiting couple family,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Lone parent family,Single family household: Lone parent family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Other single family household,Single family household: Other single family household: Other family composition,Other household types,Other household types: With dependent children,"Other household types: Other, including all full-time students and all aged 66 years and over",1 bedroom,2 bedrooms,3 bedrooms,4 or more bedrooms,1 room,2 rooms,3 rooms,4 rooms,5 rooms,6 rooms,7 rooms,8 rooms,9 or more rooms
0,E01000001,City of London,1473,52,34,32,23,90,159,132,117,114,105,89,73,83,119,102,57,57,35,837,555.0,243.0,29.0,10.0,864,86.0,53.0,35.0,10.0,1.0,2.0,2.0,3.0,639.0,33.0,1351,887.0,855.0,651.0,76.0,575.0,42.0,1.0,41.0,162.0,81.0,81.0,32.0,16.0,10.0,5.0,3.0,2.0,0.0,0.0,0.0,5.0,3.0,2.0,6.0,448.0,305.0,76.0,33.0,9.0,25.0,165.0,85.0,80.0,701.0,435.0,266.0,373.0,129.0,244.0,417.0,82.0,192.0,111.0,68.0,13.0,112.0,99.0,13.0,0.0,17.0,10.0,7.0,14.0,14.0,51.0,1.0,50.0,376.0,278.0,140.0,44.0,88.0,169.0,322.0,51.0,150.0,49.0,3.0,4.0,1.0
1,E01000002,City of London,1384,33,24,22,31,100,166,134,110,92,98,122,88,87,76,69,59,43,30,824,578.0,208.0,26.0,12.0,879,79.0,40.0,23.0,5.0,2.0,4.0,3.0,2.0,676.0,45.0,1298,900.0,870.0,656.0,61.0,595.0,40.0,4.0,36.0,174.0,63.0,111.0,30.0,12.0,9.0,6.0,4.0,2.0,0.0,0.0,0.0,3.0,0.0,3.0,3.0,386.0,233.0,85.0,27.0,0.0,41.0,131.0,53.0,78.0,744.0,430.0,314.0,409.0,101.0,308.0,369.0,57.0,162.0,104.0,46.0,12.0,107.0,93.0,11.0,3.0,25.0,13.0,12.0,18.0,18.0,46.0,3.0,43.0,409.0,265.0,100.0,52.0,97.0,237.0,288.0,64.0,60.0,67.0,3.0,0.0,7.0
2,E01000003,City of London,1613,39,32,33,23,96,187,166,144,111,113,155,118,111,86,85,50,31,33,1017,826.0,169.0,15.0,7.0,999,144.0,82.0,60.0,20.0,3.0,0.0,0.0,5.0,618.0,67.0,1509,1061.0,993.0,793.0,116.0,677.0,26.0,7.0,19.0,174.0,83.0,91.0,68.0,9.0,7.0,4.0,3.0,1.0,0.0,0.0,0.0,3.0,2.0,1.0,2.0,439.0,243.0,65.0,40.0,43.0,48.0,210.0,78.0,132.0,790.0,545.0,245.0,582.0,160.0,422.0,379.0,31.0,165.0,106.0,42.0,17.0,122.0,105.0,14.0,3.0,44.0,23.0,21.0,17.0,17.0,56.0,1.0,55.0,650.0,298.0,61.0,8.0,173.0,475.0,293.0,55.0,14.0,3.0,4.0,0.0,0.0
3,E01000005,City of London,1101,52,45,35,89,118,97,118,88,61,58,87,82,67,35,26,17,14,12,479,375.0,92.0,9.0,3.0,498,95.0,78.0,43.0,27.0,4.0,0.0,2.0,2.0,203.0,44.0,960,536.0,476.0,424.0,96.0,328.0,8.0,5.0,3.0,44.0,19.0,25.0,60.0,37.0,22.0,19.0,12.0,7.0,0.0,0.0,0.0,3.0,1.0,2.0,15.0,387.0,96.0,131.0,40.0,52.0,68.0,133.0,57.0,76.0,365.0,303.0,62.0,219.0,47.0,172.0,202.0,7.0,87.0,26.0,46.0,15.0,45.0,28.0,13.0,4.0,52.0,29.0,23.0,11.0,11.0,56.0,20.0,36.0,241.0,133.0,96.0,8.0,59.0,131.0,158.0,118.0,12.0,2.0,0.0,0.0,1.0
4,E01000006,Barking and Dagenham,1842,153,127,110,122,124,130,174,151,164,153,121,85,70,66,41,18,17,16,554,183.0,251.0,95.0,25.0,886,61.0,91.0,107.0,161.0,42.0,8.0,5.0,13.0,192.0,206.0,1428,899.0,842.0,608.0,194.0,414.0,36.0,10.0,26.0,198.0,87.0,111.0,57.0,50.0,42.0,35.0,26.0,9.0,1.0,0.0,1.0,6.0,4.0,2.0,8.0,479.0,117.0,106.0,131.0,75.0,50.0,322.0,118.0,204.0,564.0,483.0,81.0,93.0,26.0,67.0,320.0,24.0,171.0,27.0,104.0,40.0,38.0,13.0,23.0,2.0,76.0,53.0,23.0,11.0,11.0,141.0,77.0,64.0,97.0,72.0,257.0,128.0,6.0,90.0,62.0,61.0,304.0,20.0,6.0,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01035718,Westminster,2568,93,97,57,673,400,152,135,108,143,114,113,142,79,62,82,39,39,40,732,370.0,264.0,74.0,24.0,926,61.0,106.0,28.0,23.0,3.0,22.0,2.0,2.0,610.0,69.0,2307,904.0,878.0,658.0,61.0,597.0,62.0,19.0,43.0,158.0,80.0,78.0,26.0,82.0,49.0,35.0,28.0,7.0,2.0,2.0,0.0,12.0,6.0,6.0,33.0,1321.0,235.0,850.0,132.0,4.0,100.0,195.0,99.0,96.0,731.0,373.0,358.0,274.0,75.0,199.0,384.0,59.0,221.0,102.0,86.0,33.0,36.0,27.0,7.0,2.0,52.0,23.0,29.0,16.0,16.0,73.0,41.0,32.0,148.0,226.0,185.0,172.0,20.0,111.0,179.0,126.0,125.0,60.0,55.0,22.0,33.0
4990,E01035719,Westminster,1270,53,57,52,49,124,162,127,97,84,94,90,83,61,47,35,31,13,11,634,429.0,180.0,20.0,5.0,683,61.0,88.0,39.0,19.0,4.0,0.0,0.0,5.0,414.0,53.0,1101,706.0,659.0,538.0,80.0,458.0,26.0,10.0,16.0,95.0,47.0,48.0,47.0,27.0,21.0,17.0,15.0,2.0,0.0,0.0,0.0,4.0,3.0,1.0,6.0,368.0,122.0,98.0,61.0,36.0,51.0,153.0,67.0,86.0,528.0,364.0,164.0,268.0,50.0,218.0,305.0,22.0,139.0,52.0,68.0,19.0,65.0,50.0,13.0,2.0,61.0,36.0,25.0,18.0,18.0,58.0,10.0,48.0,241.0,240.0,140.0,12.0,33.0,212.0,208.0,138.0,34.0,8.0,0.0,0.0,0.0
4991,E01035720,Westminster,1218,27,68,51,58,128,162,106,64,72,119,118,72,56,33,36,15,18,15,587,374.0,183.0,29.0,1.0,678,55.0,124.0,74.0,7.0,1.0,2.0,2.0,1.0,353.0,59.0,1063,701.0,662.0,549.0,101.0,448.0,22.0,11.0,11.0,91.0,58.0,33.0,39.0,24.0,20.0,19.0,15.0,4.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0,338.0,86.0,133.0,43.0,36.0,40.0,185.0,62.0,123.0,496.0,363.0,133.0,236.0,52.0,184.0,289.0,20.0,97.0,36.0,52.0,9.0,73.0,50.0,22.0,1.0,84.0,30.0,54.0,15.0,15.0,64.0,6.0,58.0,196.0,274.0,89.0,29.0,43.0,201.0,232.0,69.0,19.0,10.0,8.0,4.0,2.0
4992,E01035721,Westminster,2326,98,93,89,99,133,206,187,166,192,237,194,173,137,85,95,67,35,40,1304,903.0,334.0,55.0,12.0,1078,95.0,139.0,92.0,21.0,4.0,1.0,5.0,5.0,606.0,110.0,2020,1168.0,1060.0,819.0,143.0,676.0,46.0,10.0,36.0,195.0,85.0,110.0,108.0,32.0,18.0,14.0,10.0,4.0,0.0,0.0,0.0,4.0,3.0,1.0,14.0,820.0,256.0,222.0,134.0,107.0,101.0,251.0,106.0,145.0,827.0,561.0,266.0,748.0,134.0,614.0,470.0,42.0,219.0,98.0,90.0,31.0,62.0,49.0,9.0,4.0,123.0,64.0,59.0,24.0,24.0,89.0,29.0,60.0,602.0,438.0,201.0,66.0,39.0,428.0,515.0,182.0,58.0,42.0,17.0,12.0,13.0
4993,E01035722,Westminster,2015,64,41,35,51,213,308,198,191,115,109,122,118,100,75,77,79,45,74,1180,818.0,317.0,37.0,8.0,1181,84.0,190.0,69.0,11.0,2.0,3.0,3.0,5.0,746.0,68.0,1873,1209.0,1161.0,911.0,96.0,815.0,46.0,15.0,31.0,204.0,83.0,121.0,48.0,35.0,18.0,14.0,8.0,6.0,0.0,0.0,0.0,4.0,3.0,1.0,17.0,629.0,264.0,218.0,80.0,30.0,37.0,205.0,79.0,126.0,973.0,646.0,327.0,645.0,179.0,466.0,409.0,33.0,185.0,107.0,64.0,14.0,120.0,114.0,5.0,1.0,56.0,20.0,36.0,15.0,15.0,129.0,18.0,111.0,621.0,390.0,126.0,42.0,177.0,440.0,374.0,120.0,40.0,8.0,9.0,3.0,11.0

In [105]:
list(merged_df_2021.columns)

['LSOA21CD',
 'Borough',
 'Total',
 'Aged 4 years and under',
 'Aged 5 to 9 years',
 'Aged 10 to 14 years',
 'Aged 15 to 19 years',
 'Aged 20 to 24 years',
 'Aged 25 to 29 years',
 'Aged 30 to 34 years',
 'Aged 35 to 39 years',
 'Aged 40 to 44 years',
 'Aged 45 to 49 years',
 'Aged 50 to 54 years',
 'Aged 55 to 59 years',
 'Aged 60 to 64 years',
 'Aged 65 to 69 years',
 'Aged 70 to 74 years',
 'Aged 75 to 79 years',
 'Aged 80 to 84 years',
 'Aged 85 years and over',
 'Total: All households',
 'No cars or vans in household',
 '1 car or van in household',
 '2 cars or vans in household',
 '3 or more cars or vans in household',
 'Total: All usual residents aged 16 years and over in employment the week before the census',
 'Less than 2km',
 '2km to less than 5km',
 '5km to less than 10km',
 '10km to less than 20km',
 '20km to less than 30km',
 '30km to less than 40km',
 '40km to less than 60km',
 '60km and over',
 'Works mainly from home',
 'Works mainly at an offshore installation, in no fixed place, or outside the UK',
 'Total: All usual residents aged 16 years and over',
 'Economically active (excluding full-time students)',
 'Economically active (excluding full-time students):In employment',
 'Economically active (excluding full-time students):In employment:Employee',
 'Economically active (excluding full-time students): In employment: Employee: Part-time',
 'Economically active (excluding full-time students): In employment: Employee: Full-time',
 'Economically active (excluding full-time students):In employment:Self-employed with employees',
 'Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time',
 'Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time',
 'Economically active (excluding full-time students):In employment:Self-employed without employees',
 'Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time',
 'Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time',
 'Economically active (excluding full-time students): Unemployed',
 'Economically active and a full-time student',
 'Economically active and a full-time student:In employment',
 'Economically active and a full-time student:In employment:Employee',
 'Economically active and a full-time student: In employment: Employee: Part-time',
 'Economically active and a full-time student: In employment: Employee: Full-time',
 'Economically active and a full-time student:In employment:Self-employed with employees',
 'Economically active and a full-time student: In employment: Self-employed with employees: Part-time',
 'Economically active and a full-time student: In employment: Self-employed with employees: Full-time',
 'Economically active and a full-time student:In employment:Self-employed without employees',
 'Economically active and a full-time student: In employment: Self-employed without employees: Part-time',
 'Economically active and a full-time student: In employment: Self-employed without employees: Full-time',
 'Economically active and a full-time student: Unemployed',
 'Economically inactive',
 'Economically inactive: Retired',
 'Economically inactive: Student',
 'Economically inactive: Looking after home or family',
 'Economically inactive: Long-term sick or disabled',
 'Economically inactive: Other',
 'Part-time',
 'Part-time: 15 hours or less worked',
 'Part-time: 16 to 30 hours worked',
 'Full-time',
 'Full-time: 31 to 48 hours worked',
 'Full-time: 49 or more hours worked',
 'One-person household',
 'One-person household: Aged 66 years and over',
 'One-person household: Other',
 'Single family household',
 'Single family household: All aged 66 years and over',
 'Single family household: Married or civil partnership couple',
 'Single family household: Married or civil partnership couple: No children',
 'Single family household: Married or civil partnership couple: Dependent children',
 'Single family household: Married or civil partnership couple: All children non-dependent',
 'Single family household: Cohabiting couple family',
 'Single family household: Cohabiting couple family: No children',
 'Single family household: Cohabiting couple family: With dependent children',
 'Single family household: Cohabiting couple family: All children non-dependent',
 'Single family household: Lone parent family',
 'Single family household: Lone parent family: With dependent children',
 'Single family household: Lone parent family: All children non-dependent',
 'Single family household: Other single family household',
 'Single family household: Other single family household: Other family composition',
 'Other household types',
 'Other household types: With dependent children',
 'Other household types: Other, including all full-time students and all aged 66 years and over',
 '1 bedroom',
 '2 bedrooms',
 '3 bedrooms',
 '4 or more bedrooms',
 '1 room',
 '2 rooms',
 '3 rooms',
 '4 rooms',
 '5 rooms',
 '6 rooms',
 '7 rooms',
 '8 rooms',
 '9 or more rooms']